const FISH_DB_EXTRA = [
// ========== 第一批：淡水路亚 - 中国本土 + 亚洲 (100种) ==========
// 中国本土特色鱼种
{id:'yellow_catfish', name:'黄颡鱼', en:'Yellow Catfish', cat:'fresh', icon:'🐟', t:{lv2:20,lv3:28,lv4:35}, r:'common', lure:'小软虫底钓'},
{id:'grass_carp', name:'草鱼', en:'Grass Carp', cat:'fresh', icon:'🐟', t:{lv2:40,lv3:60,lv4:80}, r:'common', lure:'路亚软饵/仿生蛙'},
{id:'redeye_mullet', name:'赤眼鳟', en:'Redeye Mullet', cat:'fresh', icon:'🐠', t:{lv2:25,lv3:38,lv4:50}, r:'uncommon', lure:'小型米诺/旋转片'},
{id:'mandarin_carp', name:'鳜鱼', en:'Mandarin Fish (Siniperca)', cat:'fresh', icon:'🐡', t:{lv2:30,lv3:45,lv4:60}, r:'uncommon', lure:'活饵仿生/米诺'},
{id:'bighead_carp', name:'鳙鱼', en:'Bighead Carp', cat:'fresh', icon:'🐟', t:{lv2:50,lv3:75,lv4:100}, r:'uncommon', lure:'大型软饵'},
{id:'silver_carp', name:'白鲢', en:'Silver Carp', cat:'fresh', icon:'🐟', t:{lv2:40,lv3:65,lv4:90}, r:'common', lure:'浮水路亚'},
{id:'black_carp', name:'青鱼', en:'Black Carp', cat:'fresh', icon:'🐟', t:{lv2:60,lv3:90,lv4:120}, r:'rare', lure:'大型底层路亚'},
{id:'carp_common', name:'鲤鱼', en:'Common Carp', cat:'fresh', icon:'🐟', t:{lv2:40,lv3:65,lv4:90}, r:'common', lure:'路亚软蟹/底拖'},
{id:'crucian_carp', name:'鲫鱼', en:'Crucian Carp', cat:'fresh', icon:'🐟', t:{lv2:15,lv3:22,lv4:30}, r:'common', lure:'微型软虫/小旋转片'},
{id:'wuchang_fish', name:'武昌鱼', en:'Wuchang Fish (Blunt Snout Bream)', cat:'fresh', icon:'🐟', t:{lv2:25,lv3:35,lv4:45}, r:'common', lure:'小型软饵'},
{id:'catfish_chinese', name:'鲶鱼', en:'Chinese Catfish', cat:'fresh', icon:'🐟', t:{lv2:40,lv3:65,lv4:90}, r:'common', lure:'大型软虫夜钓'},
{id:'bream_chinese', name:'鲂鱼', en:'Chinese Bream', cat:'fresh', icon:'🐟', t:{lv2:25,lv3:38,lv4:52}, r:'common', lure:'软虫底钓'},
{id:'sheatfish_china', name:'怀头鲶', en:'Amur Catfish', cat:'fresh', icon:'🐟', t:{lv2:50,lv3:80,lv4:110}, r:'rare', lure:'大型软饵/活饵'},
{id:'chinese_perch', name:'加州鲈(大口鲈)', en:'Largemouth Bass (China)', cat:'fresh', icon:'🐟', t:{lv2:28,lv3:42,lv4:58}, r:'common', lure:'VIB/软虫/米诺'},
{id:'yellow_perch_cn', name:'河鲈', en:'Eurasian Perch', cat:'fresh', icon:'🐟', t:{lv2:20,lv3:30,lv4:40}, r:'common', lure:'小型旋转片/软虫'},
{id:'amur_pike', name:'黑斑狗鱼', en:'Amur Pike', cat:'fresh', icon:'🦷', t:{lv2:45,lv3:70,lv4:95}, r:'rare', lure:'大型米诺/软鱼'},
{id:'lenok', name:'细鳞鱼', en:'Lenok', cat:'fresh', icon:'🐟', t:{lv2:30,lv3:48,lv4:65}, r:'rare', lure:'干飞/旋转片'},
{id:'chinese_sturgeon', name:'中华鲟', en:'Chinese Sturgeon', cat:'fresh', icon:'🐟', t:{lv2:100,lv3:180,lv4:280}, r:'legendary', lure:'深水底层'},
{id:'paddlefish', name:'白鲟', en:'Chinese Paddlefish', cat:'fresh', icon:'🐟', t:{lv2:120,lv3:200,lv4:300}, r:'legendary', lure:'极稀有/遗产级'},
{id:'eel_chinese', name:'鳗鲡', en:'Japanese Eel', cat:'fresh', icon:'🐍', t:{lv2:50,lv3:80,lv4:110}, r:'uncommon', lure:'夜钓底拖软虫'},
{id:'snakehead_spotted', name:'斑鳢', en:'Spotted Snakehead', cat:'fresh', icon:'🐍', t:{lv2:30,lv3:45,lv4:60}, r:'uncommon', lure:'仿生蛙/软虫'},
{id:'northern_snakehead', name:'乌鳢(黑鱼)', en:'Northern Snakehead', cat:'fresh', icon:'🐍', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'浮水蛙/软鼠'},
{id:'siniperca_knerii', name:'大眼鳜', en:'Kneri Siniperca', cat:'fresh', icon:'🐡', t:{lv2:25,lv3:38,lv4:52}, r:'rare', lure:'小型活饵仿生'},
{id:'pelteobagrus', name:'光泽黄颡', en:'Shining Yellow Catfish', cat:'fresh', icon:'🐟', t:{lv2:12,lv3:18,lv4:25}, r:'common', lure:'微型软虫'},
{id:'spinibarbus', name:'倒刺鲃', en:'Chinese Spiny Barbel', cat:'fresh', icon:'🐟', t:{lv2:30,lv3:50,lv4:70}, r:'uncommon', lure:'旋转片/小米诺'},
// 日本鱼种
{id:'japanese_seabass', name:'花鲈(日本鲈)', en:'Japanese Sea Bass', cat:'fresh', icon:'🐟', t:{lv2:45,lv3:70,lv4:95}, r:'uncommon', lure:'米诺/VIB/铅笔'},
{id:'ayu', name:'香鱼', en:'Ayu (Sweetfish)', cat:'fresh', icon:'🐟', t:{lv2:18,lv3:25,lv4:32}, r:'uncommon', lure:'友钓/小旋转片'},
{id:'yamame', name:'山女鳟', en:'Yamame Trout', cat:'fresh', icon:'🐟', t:{lv2:22,lv3:32,lv4:42}, r:'uncommon', lure:'小型旋转片/干飞'},
{id:'amago', name:'天女鱼', en:'Amago Trout', cat:'fresh', icon:'🐟', t:{lv2:20,lv3:30,lv4:40}, r:'rare', lure:'干飞/溪流小路亚'},
{id:'iwana', name:'岩鱼(白斑红点鲑)', en:'Iwana (Whitespotted Char)', cat:'fresh', icon:'🐟', t:{lv2:25,lv3:38,lv4:52}, r:'rare', lure:'干飞/小米诺'},
{id:'biwa_trout', name:'琵琶鳟', en:'Biwa Trout', cat:'fresh', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'rare', lure:'大型旋转片'},
{id:'japanese_huchen', name:'日本哲罗鱼', en:'Japanese Huchen', cat:'fresh', icon:'🐟', t:{lv2:60,lv3:90,lv4:120}, r:'legendary', lure:'大型软鱼/米诺'},
{id:'tokyo_bitterling', name:'鳑鲏', en:'Bitterling', cat:'fresh', icon:'🐠', t:{lv2:5,lv3:7,lv4:9}, r:'common', lure:'超微型路亚'},
// 东南亚热带鱼种
{id:'giant_snakehead', name:'泰国鳢', en:'Giant Snakehead', cat:'fresh', icon:'🐍', t:{lv2:50,lv3:80,lv4:110}, r:'rare', lure:'浮水蛙/大型软虫'},
{id:'toman', name:'多曼', en:'Toman (Hampala Barb)', cat:'fresh', icon:'🐟', t:{lv2:40,lv3:65,lv4:90}, r:'rare', lure:'米诺/旋转片'},
{id:'hampala_barb', name:'汉帕拉鲃', en:'Hampala Barb', cat:'fresh', icon:'🐟', t:{lv2:25,lv3:40,lv4:55}, r:'uncommon', lure:'小旋转片/米诺'},
{id:'javelin_barb', name:'矛形鲃', en:'Javelin Barb', cat:'fresh', icon:'🐟', t:{lv2:20,lv3:32,lv4:45}, r:'uncommon', lure:'小型路亚'},
{id:'jungle_perch', name:'丛林鲈', en:'Jungle Perch', cat:'fresh', icon:'🐟', t:{lv2:22,lv3:35,lv4:48}, r:'uncommon', lure:'小米诺/飞蝇'},
{id:'siamese_tiger', name:'暹罗虎鱼', en:'Siamese Tiger Fish', cat:'fresh', icon:'🐯', t:{lv2:18,lv3:28,lv4:40}, r:'rare', lure:'小型活饵仿生'},
{id:'giant_gourami', name:'巨型丝足鲈', en:'Giant Gourami', cat:'fresh', icon:'🐟', t:{lv2:30,lv3:45,lv4:60}, r:'uncommon', lure:'水面路亚/软饵'},
{id:'clown_knife', name:'皇带鱼(七星刀)', en:'Clown Knifefish', cat:'fresh', icon:'🔪', t:{lv2:40,lv3:65,lv4:90}, r:'rare', lure:'夜钓/小鱼仿生'},
{id:'temensis_peacock', name:'暗纹孔雀鲈', en:'Speckled Peacock Bass', cat:'fresh', icon:'🦚', t:{lv2:40,lv3:65,lv4:90}, r:'epic', lure:'大型米诺/popper'},
{id:'snakeskin_gourami', name:'蛇皮丝足鲈', en:'Snakeskin Gourami', cat:'fresh', icon:'🐟', t:{lv2:20,lv3:30,lv4:40}, r:'common', lure:'小型软饵'},
{id:'spot_barb', name:'宽带无须鲃', en:'Spotted Barb', cat:'fresh', icon:'🐠', t:{lv2:10,lv3:15,lv4:20}, r:'common', lure:'微型路亚'},
{id:'mahseer_tor', name:'金黄丝尾鳠', en:'Golden Tor Mahseer', cat:'fresh', icon:'🐟', t:{lv2:50,lv3:80,lv4:120}, r:'epic', lure:'旋转片/大型路亚'},
{id:'juliens_golden', name:'茱莉金鱼', en:'Julien\'s Golden Carp', cat:'fresh', icon:'🏅', t:{lv2:60,lv3:95,lv4:130}, r:'legendary', lure:'大型旋转片'},
{id:'giant_catfish_mekong', name:'湄公巨鲶', en:'Mekong Giant Catfish', cat:'fresh', icon:'🐟', t:{lv2:100,lv3:180,lv4:270}, r:'legendary', lure:'底层大型饵'},
{id:'featherback', name:'羽刀鱼', en:'Featherback Knifefish', cat:'fresh', icon:'🔪', t:{lv2:25,lv3:40,lv4:55}, r:'uncommon', lure:'夜钓小型软饵'},
// 南亚次大陆
{id:'rohu', name:'罗胡鲃', en:'Rohu', cat:'fresh', icon:'🐟', t:{lv2:40,lv3:65,lv4:90}, r:'common', lure:'旋转片/软虫'},
{id:'catla', name:'卡特拉鲃', en:'Catla', cat:'fresh', icon:'🐟', t:{lv2:50,lv3:80,lv4:110}, r:'uncommon', lure:'大型水面路亚'},
{id:'goonch', name:'鳡鲶', en:'Goonch Catfish', cat:'fresh', icon:'🦷', t:{lv2:80,lv3:130,lv4:180}, r:'epic', lure:'深水大型软饵'},
{id:'indian_mahseer', name:'印度马哈西尔', en:'Hump-backed Mahseer', cat:'fresh', icon:'🐟', t:{lv2:50,lv3:80,lv4:115}, r:'epic', lure:'大型旋转片/银片'},
// 中亚/西亚
{id:'asp_barbel', name:'贝加尔雅罗', en:'Baikal Asp', cat:'fresh', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'旋转片/小鱼饵'},
{id:'taimen_siberian', name:'西伯利亚哲罗鱼', en:'Siberian Taimen', cat:'fresh', icon:'🐟', t:{lv2:70,lv3:110,lv4:150}, r:'legendary', lure:'大型软鱼仿生'},
{id:'hucho_hucho', name:'多瑙哲罗鱼', en:'Huchen (Danube Salmon)', cat:'fresh', icon:'🐟', t:{lv2:65,lv3:100,lv4:140}, r:'epic', lure:'大型米诺/软鱼'},
// 欧洲
{id:'grayling', name:'茴鱼', en:'Grayling', cat:'fresh', icon:'🐟', t:{lv2:30,lv3:45,lv4:60}, r:'uncommon', lure:'干飞/飞蝇'},
{id:'chub', name:'鲢鳊', en:'Chub', cat:'fresh', icon:'🐟', t:{lv2:25,lv3:38,lv4:52}, r:'common', lure:'小型旋转片/软虫'},
{id:'ide', name:'欧洲雅罗鱼', en:'Ide (Orfe)', cat:'fresh', icon:'🐟', t:{lv2:30,lv3:45,lv4:60}, r:'common', lure:'旋转片/小米诺'},
{id:'asp_euro', name:'尖嘴刃鲃', en:'Asp', cat:'fresh', icon:'🐟', t:{lv2:40,lv3:60,lv4:80}, r:'uncommon', lure:'表层旋转片/爆炸饵'},
{id:'catfish_wels', name:'欧洲巨鲶', en:'Wels Catfish', cat:'fresh', icon:'🐟', t:{lv2:80,lv3:150,lv4:230}, r:'legendary', lure:'大型软饵/活饵'},
{id:'perch_redfin', name:'红鳍鲈', en:'Redfin Perch', cat:'fresh', icon:'🐟', t:{lv2:18,lv3:28,lv4:38}, r:'common', lure:'小旋转片/软虫'},
{id:'ruffe', name:'河鲈(瘤鲈)', en:'Ruffe', cat:'fresh', icon:'🐟', t:{lv2:10,lv3:15,lv4:20}, r:'common', lure:'微型软虫'},
{id:'bream_euro', name:'欧洲鳊', en:'Common Bream', cat:'fresh', icon:'🐟', t:{lv2:30,lv3:45,lv4:60}, r:'common', lure:'底层软饵'},
{id:'tench', name:'丁鲑', en:'Tench', cat:'fresh', icon:'🐟', t:{lv2:25,lv3:38,lv4:52}, r:'uncommon', lure:'底层软虫'},
{id:'burbot', name:'江鳕', en:'Burbot', cat:'fresh', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'冬季底层软饵'},
// 北美
{id:'tiger_muskie', name:'虎斑狗鱼', en:'Tiger Muskie', cat:'fresh', icon:'🐯', t:{lv2:60,lv3:90,lv4:120}, r:'epic', lure:'大型软鱼/巨型铁板'},
{id:'northern_pike', name:'北美梭鱼', en:'Northern Pike', cat:'fresh', icon:'🦷', t:{lv2:55,lv3:85,lv4:115}, r:'uncommon', lure:'大型米诺/旋转片'},
{id:'sauger', name:'沙眼鱼', en:'Sauger', cat:'fresh', icon:'🐟', t:{lv2:25,lv3:38,lv4:52}, r:'uncommon', lure:'软虫/小铁板'},
{id:'white_bass', name:'白鲈', en:'White Bass', cat:'fresh', icon:'🐟', t:{lv2:25,lv3:35,lv4:45}, r:'common', lure:'小型旋转片'},
{id:'striped_bass', name:'条纹鲈', en:'Striped Bass', cat:'fresh', icon:'🐟', t:{lv2:45,lv3:70,lv4:100}, r:'uncommon', lure:'大型米诺/铁板'},
{id:'yellow_perch', name:'黄鲈', en:'Yellow Perch', cat:'fresh', icon:'🐟', t:{lv2:18,lv3:27,lv4:35}, r:'common', lure:'小软虫/小旋转片'},
{id:'flathead_catfish', name:'扁头鲶', en:'Flathead Catfish', cat:'fresh', icon:'🐟', t:{lv2:50,lv3:80,lv4:110}, r:'uncommon', lure:'大型软虫夜钓'},
{id:'channel_catfish', name:'斑点叉尾鮰', en:'Channel Catfish', cat:'fresh', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'common', lure:'底层软饵'},
{id:'blue_catfish', name:'蓝鲶', en:'Blue Catfish', cat:'fresh', icon:'🐟', t:{lv2:50,lv3:80,lv4:120}, r:'uncommon', lure:'大型底层软饵'},
{id:'muskellunge', name:'北美狗鱼王', en:'Muskellunge', cat:'fresh', icon:'🦷', t:{lv2:75,lv3:110,lv4:150}, r:'epic', lure:'巨型软鱼/大米诺'},
{id:'bowfin', name:'弓鳍鱼', en:'Bowfin', cat:'fresh', icon:'🐟', t:{lv2:40,lv3:60,lv4:80}, r:'uncommon', lure:'大型软虫'},
{id:'longnose_gar', name:'长吻雀鳝', en:'Longnose Gar', cat:'fresh', icon:'🦷', t:{lv2:60,lv3:95,lv4:130}, r:'uncommon', lure:'绳饵/活饵'},
{id:'alligator_gar', name:'鳄雀鳝', en:'Alligator Gar', cat:'fresh', icon:'🐊', t:{lv2:100,lv3:160,lv4:230}, r:'legendary', lure:'大型绳饵/死鱼'},
{id:'freshwater_drum', name:'淡水石首鱼', en:'Freshwater Drum', cat:'fresh', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'common', lure:'底层软虫/铁板'},
{id:'saugeye', name:'杂交沙眼鱼', en:'Saugeye', cat:'fresh', icon:'🐟', t:{lv2:28,lv3:42,lv4:58}, r:'uncommon', lure:'软虫/小铁板'},
// 南美
{id:'pirarucu', name:'象鱼(巨骨舌鱼)', en:'Pirarucu / Arapaima', cat:'fresh', icon:'🐟', t:{lv2:120,lv3:200,lv4:300}, r:'legendary', lure:'大型水面路亚'},
{id:'bicuda', name:'南美梭鱼', en:'Bicuda', cat:'fresh', icon:'🐟', t:{lv2:40,lv3:65,lv4:90}, r:'uncommon', lure:'快速米诺'},
{id:'traira', name:'虎鱼鲈', en:'Traira (Wolf Fish)', cat:'fresh', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'水面软饵'},
{id:'tucunare', name:'图库纳雷孔雀鲈', en:'Tucunare Peacock Bass', cat:'fresh', icon:'🦚', t:{lv2:30,lv3:50,lv4:70}, r:'rare', lure:'米诺/Popper'},
{id:'pirapitinga', name:'皮拉皮汀加果鲤', en:'Pirapitinga', cat:'fresh', icon:'🐟', t:{lv2:40,lv3:65,lv4:90}, r:'uncommon', lure:'大型路亚'},
{id:'pacu', name:'红腹食人鱼(帕库)', en:'Pacu', cat:'fresh', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'水面路亚/果实仿生'},
{id:'piranha_red', name:'红腹食人鱼', en:'Red-bellied Piranha', cat:'fresh', icon:'🦷', t:{lv2:18,lv3:25,lv4:33}, r:'uncommon', lure:'小型软饵'},
{id:'dourado_golden', name:'金多拉多', en:'Golden Dorado', cat:'fresh', icon:'🏅', t:{lv2:45,lv3:72,lv4:100}, r:'epic', lure:'大型米诺/旋转片'},
{id:'surubim', name:'苏鲁宾鲶', en:'Surubim Catfish', cat:'fresh', icon:'🐟', t:{lv2:60,lv3:100,lv4:140}, r:'rare', lure:'大型底层软饵'},
{id:'matrinxa', name:'马特林沙', en:'Matrinxa', cat:'fresh', icon:'🐟', t:{lv2:30,lv3:48,lv4:65}, r:'uncommon', lure:'旋转片/小米诺'},
// 非洲
{id:'tigerfish_goliath', name:'巨型虎鱼', en:'Goliath Tigerfish', cat:'fresh', icon:'🦷', t:{lv2:80,lv3:130,lv4:180}, r:'legendary', lure:'大型银片/活饵'},
{id:'vundu', name:'武士鲶', en:'Vundu Catfish', cat:'fresh', icon:'🐟', t:{lv2:60,lv3:100,lv4:145}, r:'epic', lure:'大型底层软饵'},
{id:'african_tigerfish', name:'非洲虎鱼', en:'African Tigerfish', cat:'fresh', icon:'🦷', t:{lv2:35,lv3:55,lv4:75}, r:'rare', lure:'快速旋转片/米诺'},
{id:'nile_tilapia', name:'尼罗罗非鱼', en:'Nile Tilapia', cat:'fresh', icon:'🐟', t:{lv2:20,lv3:32,lv4:45}, r:'common', lure:'小型软虫/旋转片'},
{id:'african_lungfish', name:'非洲肺鱼', en:'African Lungfish', cat:'fresh', icon:'🐟', t:{lv2:60,lv3:100,lv4:140}, r:'rare', lure:'底层软饵/夜钓'},
{id:'sharptooth_catfish', name:'尖齿鲶', en:'Sharptooth Catfish', cat:'fresh', icon:'🐟', t:{lv2:50,lv3:80,lv4:115}, r:'uncommon', lure:'大型软饵'},
{id:'bream_african', name:'非洲鲷', en:'African Bream', cat:'fresh', icon:'🐟', t:{lv2:20,lv3:32,lv4:45}, r:'common', lure:'底层软虫'},
{id:'yellowfish', name:'黄鱼(南非)', en:'Yellowfish', cat:'fresh', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'旋转片/飞蝇'},
// 澳洲/大洋洲
{id:'saratoga', name:'萨拉托加骨舌鱼', en:'Saratoga / Australian Arowana', cat:'fresh', icon:'🐟', t:{lv2:55,lv3:85,lv4:115}, r:'epic', lure:'水面路亚/蛙'},
{id:'golden_perch', name:'金鲈', en:'Golden Perch', cat:'fresh', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'旋转片/软虫'},
{id:'macquarie_perch', name:'麦奎利鲈', en:'Macquarie Perch', cat:'fresh', icon:'🐟', t:{lv2:20,lv3:30,lv4:40}, r:'rare', lure:'小型旋转片/飞蝇'},
{id:'silver_perch', name:'银鲈', en:'Silver Perch', cat:'fresh', icon:'🐟', t:{lv2:25,lv3:38,lv4:52}, r:'uncommon', lure:'小型路亚'},
{id:'jungle_perch_au', name:'丛林鲈(澳)', en:'Australian Jungle Perch', cat:'fresh', icon:'🐟', t:{lv2:22,lv3:35,lv4:48}, r:'rare', lure:'小米诺/飞蝇'},
// 北极/亚北极
{id:'lake_trout', name:'湖鳟', en:'Lake Trout', cat:'fresh', icon:'🐟', t:{lv2:45,lv3:72,lv4:100}, r:'uncommon', lure:'大型旋转片/铁板'},
{id:'dolly_varden', name:'花羔红点鲑', en:'Dolly Varden', cat:'fresh', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'rare', lure:'旋转片/飞蝇'},
{id:'brook_trout', name:'布鲁克鳟', en:'Brook Trout', cat:'fresh', icon:'🐟', t:{lv2:22,lv3:35,lv4:50}, r:'uncommon', lure:'飞蝇/旋转片'},
{id:'coho_salmon', name:'银鲑', en:'Coho Salmon', cat:'fresh', icon:'🐟', t:{lv2:50,lv3:75,lv4:100}, r:'uncommon', lure:'旋转片/铁板'},
{id:'sockeye_salmon', name:'红鲑', en:'Sockeye Salmon', cat:'fresh', icon:'🐟', t:{lv2:40,lv3:60,lv4:80}, r:'uncommon', lure:'飞蝇/旋转片'},
{id:'chum_salmon', name:'马苏大马哈鱼', en:'Chum Salmon', cat:'fresh', icon:'🐟', t:{lv2:45,lv3:70,lv4:95}, r:'uncommon', lure:'旋转片/铁板'},
{id:'pink_salmon', name:'粉红鲑', en:'Pink Salmon', cat:'fresh', icon:'🐟', t:{lv2:38,lv3:58,lv4:78}, r:'common', lure:'小旋转片'},
{id:'landlocked_salmon', name:'陆封大西洋鲑', en:'Landlocked Atlantic Salmon', cat:'fresh', icon:'🐟', t:{lv2:40,lv3:62,lv4:85}, r:'rare', lure:'旋转片/飞蝇'},
{id:'inconnu', name:'白鲑鱼王', en:'Inconnu (Sheefish)', cat:'fresh', icon:'🐟', t:{lv2:50,lv3:80,lv4:115}, r:'rare', lure:'大型旋转片'},

// ========== 第二批：近岸海水路亚 salt (100种) ==========
// 珊瑚礁 / 近岸 - 亚洲/印太
{id:'threadfin_salmon', name:'马友鱼', en:'Threadfin Salmon', cat:'salt', icon:'🐟', t:{lv2:45,lv3:70,lv4:95}, r:'uncommon', lure:'米诺/旋转片'},
{id:'giant_trevally_small', name:'钻石鲹(小GT)', en:'Giant Trevally (juvenile)', cat:'salt', icon:'🐠', t:{lv2:40,lv3:65,lv4:90}, r:'uncommon', lure:'铁板/软饵'},
{id:'golden_trevally', name:'金带鲹', en:'Golden Trevally', cat:'salt', icon:'🟡', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'旋转片/软饵'},
{id:'diamond_trevally', name:'钻石针鲹', en:'Diamond Trevally', cat:'salt', icon:'💎', t:{lv2:30,lv3:48,lv4:65}, r:'uncommon', lure:'小铁板/旋转片'},
{id:'bludger_trevally', name:'侧纹鲹', en:'Bludger Trevally', cat:'salt', icon:'🐠', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'铁板'},
{id:'bigeye_trevally', name:'大眼鲹', en:'Bigeye Trevally', cat:'salt', icon:'👁', t:{lv2:30,lv3:48,lv4:65}, r:'common', lure:'铁板/旋转片'},
{id:'brassy_trevally', name:'黄带鲹', en:'Brassy Trevally', cat:'salt', icon:'🐠', t:{lv2:28,lv3:44,lv4:60}, r:'common', lure:'小铁板'},
{id:'snub_nose_dart', name:'短吻鲳鲹', en:'Snubnose Dart', cat:'salt', icon:'🐠', t:{lv2:25,lv3:38,lv4:52}, r:'uncommon', lure:'小型路亚/旋转片'},
{id:'pompano', name:'印度鲳鲹', en:'Indian Pompano', cat:'salt', icon:'🐠', t:{lv2:30,lv3:45,lv4:60}, r:'uncommon', lure:'小铁板/软饵'},
{id:'giant_queenfish', name:'大叉尾鲹', en:'Giant Queenfish', cat:'salt', icon:'🐠', t:{lv2:45,lv3:70,lv4:95}, r:'rare', lure:'表层米诺/铁板'},
{id:'doublespotted_queenfish', name:'双斑叉尾鲹', en:'Double-spotted Queenfish', cat:'salt', icon:'🐠', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'表层路亚'},
{id:'longtail_tuna', name:'长尾金枪鱼', en:'Longtail Tuna', cat:'salt', icon:'🐟', t:{lv2:50,lv3:75,lv4:100}, r:'uncommon', lure:'铁板/羽毛饵'},
{id:'mackerel_tuna', name:'鲔(炮弹鱼)', en:'Mackerel Tuna', cat:'salt', icon:'🐟', t:{lv2:35,lv3:52,lv4:70}, r:'common', lure:'快速铁板'},
{id:'narrow_barred_mackerel', name:'窄带马鲛', en:'Narrow-barred Spanish Mackerel', cat:'salt', icon:'🐟', t:{lv2:55,lv3:85,lv4:115}, r:'uncommon', lure:'快速米诺/铁板'},
{id:'school_mackerel', name:'澳洲学校马鲛', en:'School Mackerel', cat:'salt', icon:'🐟', t:{lv2:40,lv3:62,lv4:85}, r:'common', lure:'旋转片/羽毛饵'},
{id:'coral_trout', name:'珊瑚鳟', en:'Coral Trout', cat:'salt', icon:'🐡', t:{lv2:35,lv3:55,lv4:75}, r:'rare', lure:'软饵底跳/铁板'},
{id:'leopard_coral_trout', name:'豹纹珊瑚鳟', en:'Leopard Coral Trout', cat:'salt', icon:'🐡', t:{lv2:38,lv3:58,lv4:78}, r:'rare', lure:'铁板/活饵仿生'},
{id:'snapper_mangrove', name:'红鳍笛鲷', en:'Mangrove Jack', cat:'salt', icon:'🐠', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'米诺/软饵'},
{id:'fingermark_snapper', name:'金带笛鲷', en:'Fingermark Snapper', cat:'salt', icon:'🐠', t:{lv2:40,lv3:65,lv4:90}, r:'rare', lure:'铁板/软饵'},
{id:'emperor_fish', name:'裸顶鲷(皇帝鱼)', en:'Emperor Fish', cat:'salt', icon:'👑', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'底层软饵/铁板'},
{id:'longnose_emperor', name:'长嘴裸顶鲷', en:'Longnose Emperor', cat:'salt', icon:'👑', t:{lv2:30,lv3:48,lv4:65}, r:'uncommon', lure:'软蟹/铁板'},
{id:'sweetlip_oriental', name:'东方胡椒鲷', en:'Oriental Sweetlips', cat:'salt', icon:'🐠', t:{lv2:28,lv3:42,lv4:58}, r:'uncommon', lure:'底层软饵'},
{id:'painted_sweetlip', name:'花斑胡椒鲷', en:'Painted Sweetlips', cat:'salt', icon:'🐠', t:{lv2:30,lv3:45,lv4:60}, r:'uncommon', lure:'软蟹/底层'},
{id:'spangled_emperor', name:'星斑裸顶鲷', en:'Spangled Emperor', cat:'salt', icon:'✨', t:{lv2:40,lv3:62,lv4:85}, r:'rare', lure:'铁板/软饵'},
{id:'black_bass_coral', name:'珊瑚黑鲈', en:'Black Bass (Coral)', cat:'salt', icon:'🐠', t:{lv2:35,lv3:55,lv4:75}, r:'rare', lure:'软饵/铁板'},
{id:'humpback_grouper', name:'驼背鲈', en:'Humpback Grouper', cat:'salt', icon:'🐡', t:{lv2:30,lv3:48,lv4:65}, r:'rare', lure:'活饵仿生/软饵'},
{id:'camouflage_grouper', name:'伪装石斑', en:'Camouflage Grouper', cat:'salt', icon:'🐡', t:{lv2:35,lv3:55,lv4:75}, r:'rare', lure:'软饵底跳'},
{id:'peacock_grouper', name:'孔雀石斑', en:'Peacock Grouper', cat:'salt', icon:'🦚', t:{lv2:30,lv3:48,lv4:65}, r:'rare', lure:'铁板/软饵'},
{id:'black_grouper', name:'黑石斑', en:'Black Grouper', cat:'salt', icon:'🐡', t:{lv2:45,lv3:72,lv4:100}, r:'epic', lure:'大型铁板/软饵'},
{id:'nassau_grouper', name:'拿骚石斑', en:'Nassau Grouper', cat:'salt', icon:'🐡', t:{lv2:40,lv3:65,lv4:90}, r:'epic', lure:'铁板/活饵仿生'},
{id:'gag_grouper', name:'壁虎石斑', en:'Gag Grouper', cat:'salt', icon:'🐡', t:{lv2:45,lv3:70,lv4:95}, r:'rare', lure:'铁板/软饵'},
{id:'scamp_grouper', name:'斑点石斑', en:'Scamp Grouper', cat:'salt', icon:'🐡', t:{lv2:40,lv3:62,lv4:85}, r:'rare', lure:'底层铁板'},
{id:'yellowmouth_grouper', name:'黄口石斑', en:'Yellowmouth Grouper', cat:'salt', icon:'🐡', t:{lv2:35,lv3:55,lv4:75}, r:'rare', lure:'软饵/铁板'},
{id:'barramundi_cod', name:'巴拉蒙迪鳕石斑', en:'Barramundi Cod', cat:'salt', icon:'🐡', t:{lv2:40,lv3:65,lv4:90}, r:'epic', lure:'大型软饵'},
// 日本沿岸
{id:'hirame', name:'牙鲆', en:'Hirame (Japanese Flounder)', cat:'salt', icon:'🫓', t:{lv2:40,lv3:62,lv4:85}, r:'uncommon', lure:'软鱼底拖'},
{id:'madai', name:'真鲷', en:'Madai (Japanese Red Seabream)', cat:'salt', icon:'🐠', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'铁板鲷/软饵'},
{id:'kurodai', name:'黑鲷', en:'Kurodai (Black Seabream)', cat:'salt', icon:'🐠', t:{lv2:28,lv3:42,lv4:58}, r:'common', lure:'岸钓小路亚'},
{id:'mebarufish', name:'日本鲬', en:'Mebaru (Sebastes Fish)', cat:'salt', icon:'🐠', t:{lv2:18,lv3:28,lv4:38}, r:'common', lure:'软虫底跳'},
{id:'aji', name:'竹荚鱼', en:'Aji (Horse Mackerel)', cat:'salt', icon:'🐟', t:{lv2:20,lv3:30,lv4:40}, r:'common', lure:'AJING软虫'},
{id:'saba', name:'鲭鱼', en:'Saba (Chub Mackerel)', cat:'salt', icon:'🐟', t:{lv2:30,lv3:45,lv4:60}, r:'common', lure:'金属铁板/羽毛'},
{id:'hamachi', name:'黄尾鰤', en:'Hamachi (Japanese Amberjack)', cat:'salt', icon:'🐟', t:{lv2:55,lv3:85,lv4:120}, r:'uncommon', lure:'大型铁板'},
{id:'kanpachi', name:'大平鲹', en:'Kanpachi (Greater Amberjack)', cat:'salt', icon:'🐟', t:{lv2:60,lv3:95,lv4:130}, r:'rare', lure:'深水铁板'},
{id:'hiramasa', name:'平政鰤', en:'Hiramasa (Yellowtail Amberjack)', cat:'salt', icon:'🐟', t:{lv2:65,lv3:100,lv4:140}, r:'rare', lure:'大型铁板'},
{id:'katsuo', name:'鲣鱼', en:'Katsuo (Skipjack Tuna)', cat:'salt', icon:'🐟', t:{lv2:40,lv3:62,lv4:85}, r:'common', lure:'羽毛饵/铁板'},
{id:'tachi_uo', name:'带鱼(太刀鱼)', en:'Tachiuo (Largehead Hairtail)', cat:'salt', icon:'🗡', t:{lv2:70,lv3:110,lv4:150}, r:'common', lure:'夜钓金属铁板'},
{id:'suzuki', name:'七星鲈', en:'Suzuki (Japanese Sea Bass)', cat:'salt', icon:'🐟', t:{lv2:45,lv3:70,lv4:95}, r:'uncommon', lure:'米诺/VIB/软饵'},
// 中国近岸
{id:'large_yellow_croaker', name:'大黄鱼', en:'Large Yellow Croaker', cat:'salt', icon:'🟡', t:{lv2:30,lv3:48,lv4:65}, r:'rare', lure:'小铁板/软虫'},
{id:'small_yellow_croaker', name:'小黄鱼', en:'Small Yellow Croaker', cat:'salt', icon:'🟡', t:{lv2:18,lv3:26,lv4:35}, r:'common', lure:'小铁板'},
{id:'silver_pomfret', name:'银鲳', en:'Silver Pomfret', cat:'salt', icon:'🪙', t:{lv2:25,lv3:38,lv4:52}, r:'uncommon', lure:'软饵轻触底'},
{id:'golden_pomfret', name:'金鲳', en:'Golden Pomfret', cat:'salt', icon:'🪙', t:{lv2:30,lv3:48,lv4:65}, r:'uncommon', lure:'铁板/软饵'},
{id:'chinese_seabream', name:'二长棘犁齿鲷', en:'Red Bigeye Seabream', cat:'salt', icon:'🐠', t:{lv2:20,lv3:32,lv4:45}, r:'common', lure:'小软虫'},
{id:'blue_spotted_mullet', name:'鲻鱼', en:'Flathead Grey Mullet', cat:'salt', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'common', lure:'软虫表层'},
{id:'spotted_scat', name:'金钱鱼', en:'Spotted Scat', cat:'salt', icon:'💰', t:{lv2:18,lv3:28,lv4:38}, r:'common', lure:'小型软饵'},
{id:'puffer_tiger', name:'暗纹东方鲀', en:'Tiger Pufferfish', cat:'salt', icon:'🐡', t:{lv2:25,lv3:38,lv4:52}, r:'uncommon', lure:'软虫底钓'},
// 东南亚沿岸
{id:'cubera_snapper', name:'古巴笛鲷', en:'Cubera Snapper', cat:'salt', icon:'🐠', t:{lv2:50,lv3:80,lv4:120}, r:'epic', lure:'大型软饵/铁板'},
{id:'two_spot_red_snapper', name:'双斑笛鲷', en:'Two-spot Red Snapper', cat:'salt', icon:'🐠', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'软饵/铁板'},
{id:'john_dory', name:'麦氏刺鲬', en:'John Dory', cat:'salt', icon:'🐠', t:{lv2:30,lv3:45,lv4:60}, r:'uncommon', lure:'活饵仿生'},
{id:'permit', name:'许氏鲳鲹', en:'Permit', cat:'salt', icon:'🐠', t:{lv2:45,lv3:70,lv4:95}, r:'rare', lure:'软蟹飞钓'},
{id:'roosterfish', name:'公鸡鱼', en:'Roosterfish', cat:'salt', icon:'🐠', t:{lv2:60,lv3:90,lv4:125}, r:'epic', lure:'大型米诺/popper'},
{id:'ladyfish', name:'海鲢属', en:'Ladyfish', cat:'salt', icon:'🐟', t:{lv2:35,lv3:52,lv4:70}, r:'common', lure:'快速路亚/铁板'},
{id:'bluefish', name:'蓝鱼', en:'Bluefish', cat:'salt', icon:'🐟', t:{lv2:40,lv3:62,lv4:85}, r:'common', lure:'快速旋转片'},
{id:'jack_crevalle', name:'叉尾鲹', en:'Jack Crevalle', cat:'salt', icon:'🐠', t:{lv2:40,lv3:65,lv4:90}, r:'uncommon', lure:'快速铁板/topwater'},
{id:'florida_pompano', name:'佛罗里达鲳鲹', en:'Florida Pompano', cat:'salt', icon:'🐠', t:{lv2:30,lv3:45,lv4:60}, r:'uncommon', lure:'小铁板/软蟹'},
{id:'spotted_seatrout', name:'斑点海鳟', en:'Spotted Seatrout', cat:'salt', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'common', lure:'软虫/米诺'},
{id:'snook_common', name:'白花鱼', en:'Common Snook', cat:'salt', icon:'🐟', t:{lv2:50,lv3:80,lv4:115}, r:'uncommon', lure:'米诺/软饵'},
{id:'fat_snook', name:'胖梭鲈', en:'Fat Snook', cat:'salt', icon:'🐟', t:{lv2:45,lv3:70,lv4:95}, r:'uncommon', lure:'小型米诺'},
{id:'redfish', name:'红拟石首鱼', en:'Red Drum / Redfish', cat:'salt', icon:'🔴', t:{lv2:45,lv3:72,lv4:100}, r:'uncommon', lure:'软蟹/米诺/铁板'},
{id:'sheepshead', name:'羊头鱼', en:'Sheepshead', cat:'salt', icon:'🐟', t:{lv2:30,lv3:45,lv4:60}, r:'uncommon', lure:'软蟹/藤壶仿生'},
{id:'mangrove_snapper', name:'红树林笛鲷', en:'Mangrove Snapper', cat:'salt', icon:'🐠', t:{lv2:30,lv3:48,lv4:65}, r:'common', lure:'软饵/小铁板'},
{id:'lane_snapper', name:'草带笛鲷', en:'Lane Snapper', cat:'salt', icon:'🐠', t:{lv2:22,lv3:35,lv4:48}, r:'common', lure:'小软饵'},
{id:'gray_snapper', name:'灰笛鲷', en:'Gray Snapper', cat:'salt', icon:'🐠', t:{lv2:25,lv3:40,lv4:55}, r:'common', lure:'小软饵/铁板'},
{id:'mutton_snapper', name:'羊肉笛鲷', en:'Mutton Snapper', cat:'salt', icon:'🐠', t:{lv2:40,lv3:65,lv4:90}, r:'uncommon', lure:'铁板/软饵'},
// 地中海/欧洲沿岸
{id:'european_bass', name:'欧洲鲈鱼', en:'European Sea Bass', cat:'salt', icon:'🐟', t:{lv2:40,lv3:62,lv4:85}, r:'uncommon', lure:'米诺/软虫/旋转片'},
{id:'gilt_head_bream', name:'金头鲷', en:'Gilt-head Bream (Dorada)', cat:'salt', icon:'🐠', t:{lv2:30,lv3:48,lv4:65}, r:'uncommon', lure:'软蟹/小铁板'},
{id:'atlantic_bonito', name:'大西洋鲣', en:'Atlantic Bonito', cat:'salt', icon:'🐟', t:{lv2:40,lv3:62,lv4:85}, r:'common', lure:'快速旋转片/铁板'},
{id:'dentex', name:'牙鲷', en:'Dentex', cat:'salt', icon:'🦷', t:{lv2:45,lv3:70,lv4:95}, r:'rare', lure:'深水铁板/软饵'},
{id:'greater_amberjack', name:'大西洋俊鲹', en:'Greater Amberjack', cat:'salt', icon:'🐟', t:{lv2:60,lv3:95,lv4:130}, r:'rare', lure:'大型铁板/活饵'},
{id:'leerfish', name:'枪形鱼', en:'Leerfish (Garrick)', cat:'salt', icon:'🐟', t:{lv2:55,lv3:85,lv4:115}, r:'rare', lure:'快速表层路亚'},
{id:'meagre', name:'大西洋黄鱼', en:'Meagre / Mulloway', cat:'salt', icon:'🐟', t:{lv2:55,lv3:90,lv4:130}, r:'rare', lure:'大型米诺/软鱼'},
// 非洲沿岸
{id:'king_mackerel_sa', name:'国王马鲛', en:'King Mackerel', cat:'salt', icon:'🐟', t:{lv2:60,lv3:95,lv4:130}, r:'uncommon', lure:'快速铁板/米诺'},
{id:'kob_fish', name:'南非石首鱼', en:'Kob (South African Mulloway)', cat:'salt', icon:'🐟', t:{lv2:50,lv3:80,lv4:115}, r:'rare', lure:'大型软饵/米诺'},
{id:'garrick_sa', name:'南非梭形鱼', en:'Garrick (Leerfish)', cat:'salt', icon:'🐟', t:{lv2:55,lv3:85,lv4:115}, r:'rare', lure:'表层米诺'},
{id:'giant_kingfish_sa', name:'金带拟鲹', en:'Giant Kingfish', cat:'salt', icon:'🐠', t:{lv2:50,lv3:80,lv4:110}, r:'rare', lure:'铁板/软饵'},
{id:'blacktail_snapper', name:'黑尾笛鲷', en:'Blacktail Snapper', cat:'salt', icon:'🐠', t:{lv2:28,lv3:44,lv4:60}, r:'common', lure:'软饵/小铁板'},
// 澳洲沿岸
{id:'barramundi_salt', name:'银鲈(海水)', en:'Barramundi (Salt)', cat:'salt', icon:'🐟', t:{lv2:50,lv3:80,lv4:120}, r:'uncommon', lure:'表层路亚/米诺'},
{id:'queenfish_au', name:'澳洲皇后鱼', en:'Queenfish (Australia)', cat:'salt', icon:'🐠', t:{lv2:40,lv3:65,lv4:90}, r:'uncommon', lure:'表层米诺'},
{id:'nannygai', name:'红鱼(澳)', en:'Nannygai (Red Fish)', cat:'salt', icon:'🔴', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'铁板'},
{id:'snapper_au', name:'澳洲真鲷', en:'Australasian Snapper', cat:'salt', icon:'🐠', t:{lv2:40,lv3:65,lv4:90}, r:'uncommon', lure:'铁板/软饵'},
{id:'jewfish_au', name:'金线鱼(澳)', en:'Jewfish (Mulloway)', cat:'salt', icon:'🐟', t:{lv2:55,lv3:90,lv4:130}, r:'rare', lure:'大型米诺/软鱼'},
{id:'flathead_au', name:'扁头鱼(澳)', en:'Dusky Flathead', cat:'salt', icon:'🫓', t:{lv2:40,lv3:65,lv4:90}, r:'uncommon', lure:'软鱼底拖'},
{id:'dart_fish_au', name:'澳洲飞镖鱼', en:'Swallowtail Dart', cat:'salt', icon:'🐠', t:{lv2:25,lv3:40,lv4:55}, r:'common', lure:'小铁板'},
{id:'longtail_tuna_au', name:'澳洲长尾金枪', en:'Longtail Tuna (Australia)', cat:'salt', icon:'🐟', t:{lv2:50,lv3:75,lv4:100}, r:'uncommon', lure:'铁板/羽毛'},
// 热带水面鱼
{id:'gt_baby', name:'浪人鲹幼鱼', en:'GT Baby (Giant Trevally Sub-adult)', cat:'salt', icon:'🐠', t:{lv2:30,lv3:50,lv4:75}, r:'uncommon', lure:'小型popper/铁板'},
{id:'yellowspot_trevally', name:'黄点鲹', en:'Yellowspotted Trevally', cat:'salt', icon:'🐠', t:{lv2:28,lv3:44,lv4:60}, r:'common', lure:'小铁板'},
{id:'gold_spot_trevally', name:'金斑鲹', en:'Gold-spotted Trevally', cat:'salt', icon:'🐠', t:{lv2:25,lv3:40,lv4:55}, r:'common', lure:'铁板/旋转片'},
{id:'torpedo_scad', name:'粗皮鲹', en:'Torpedo Scad', cat:'salt', icon:'🐠', t:{lv2:20,lv3:30,lv4:40}, r:'common', lure:'小铁板'},
{id:'wolf_herring', name:'沙丁鱼形鲱', en:'Wolf Herring', cat:'salt', icon:'🦷', t:{lv2:40,lv3:62,lv4:85}, r:'uncommon', lure:'快速表层路亚'},

// ========== 第三批：近岸salt补充 + 远洋/深海sea (100种) ==========
// --- salt 补充 ---
{id:'saury_pacific', name:'秋刀鱼', en:'Pacific Saury', cat:'salt', icon:'🗡', t:{lv2:28,lv3:35,lv4:40}, r:'common', lure:'微型铁板/羽毛'},
{id:'garfish_euro', name:'颌针鱼', en:'Garfish', cat:'salt', icon:'🗡', t:{lv2:30,lv3:45,lv4:60}, r:'common', lure:'表层米诺'},
{id:'belone_belone', name:'大西洋颌针鱼', en:'Atlantic Needlefish', cat:'salt', icon:'🗡', t:{lv2:35,lv3:52,lv4:70}, r:'common', lure:'细长米诺'},
{id:'flyingfish', name:'飞鱼', en:'Flying Fish', cat:'salt', icon:'✈', t:{lv2:25,lv3:38,lv4:52}, r:'uncommon', lure:'夜间灯光'},
{id:'halfbeak', name:'剑颌鱼', en:'Halfbeak', cat:'salt', icon:'🗡', t:{lv2:22,lv3:33,lv4:45}, r:'common', lure:'微型路亚'},
{id:'pacific_bluefin_coast', name:'太平洋蓝鳍岸钓', en:'Pacific Bluefin (Coastal)', cat:'salt', icon:'🐟', t:{lv2:60,lv3:100,lv4:150}, r:'epic', lure:'岸投大型铁板'},
{id:'wahoo_coastal', name:'白甘岸钓', en:'Wahoo (Coastal)', cat:'salt', icon:'🐟', t:{lv2:60,lv3:95,lv4:130}, r:'epic', lure:'快速铁板'},
{id:'giant_barracuda', name:'巨型梭鱼', en:'Great Barracuda', cat:'salt', icon:'🦷', t:{lv2:60,lv3:95,lv4:130}, r:'rare', lure:'快速银片/铁板'},
{id:'pickhandle_barracuda', name:'大扁梭鱼', en:'Pickhandle Barracuda', cat:'salt', icon:'🦷', t:{lv2:50,lv3:80,lv4:110}, r:'uncommon', lure:'快速铁板'},
{id:'chevron_barracuda', name:'箭形梭鱼', en:'Chevron Barracuda', cat:'salt', icon:'🦷', t:{lv2:40,lv3:62,lv4:85}, r:'uncommon', lure:'旋转片/铁板'},
{id:'pacific_sierra', name:'太平洋马鲛', en:'Pacific Sierra Mackerel', cat:'salt', icon:'🐟', t:{lv2:45,lv3:70,lv4:95}, r:'uncommon', lure:'铁板'},
{id:'cero_mackerel', name:'塞罗马鲛', en:'Cero Mackerel', cat:'salt', icon:'🐟', t:{lv2:45,lv3:70,lv4:95}, r:'uncommon', lure:'快速铁板'},
{id:'atlantic_spanish_mack', name:'大西洋西班牙马鲛', en:'Atlantic Spanish Mackerel', cat:'salt', icon:'🐟', t:{lv2:50,lv3:78,lv4:105}, r:'uncommon', lure:'铁板/羽毛'},
{id:'wahoo_indo', name:'印太白甘鱼', en:'Indo-Pacific Wahoo', cat:'salt', icon:'🐟', t:{lv2:60,lv3:95,lv4:130}, r:'epic', lure:'快速铁板'},
{id:'tarpon_small', name:'大海鲢(小型)', en:'Tarpon (Juvenile)', cat:'salt', icon:'🐟', t:{lv2:50,lv3:80,lv4:120}, r:'rare', lure:'飞蝇/软饵'},
{id:'ox_eye_tarpon', name:'大眼海鲢', en:'Ox-eye Tarpon', cat:'salt', icon:'👁', t:{lv2:40,lv3:65,lv4:90}, r:'rare', lure:'软饵/米诺'},
{id:'milkfish', name:'遮目鱼', en:'Milkfish', cat:'salt', icon:'🐟', t:{lv2:40,lv3:65,lv4:90}, r:'uncommon', lure:'小型路亚'},
{id:'surgeonfish', name:'刺尾鱼', en:'Surgeonfish', cat:'salt', icon:'🐠', t:{lv2:18,lv3:28,lv4:38}, r:'common', lure:'软藻仿生'},
{id:'parrotfish', name:'鹦哥鱼', en:'Parrotfish', cat:'salt', icon:'🦜', t:{lv2:25,lv3:40,lv4:55}, r:'common', lure:'软珊瑚仿生'},
{id:'wrasse_napoleonfish', name:'拿破仑鱼', en:'Napoleon Wrasse', cat:'salt', icon:'👑', t:{lv2:60,lv3:100,lv4:150}, r:'epic', lure:'大型软饵'},
{id:'bluespine_unicornfish', name:'蓝棘独角鱼', en:'Bluespine Unicornfish', cat:'salt', icon:'🦄', t:{lv2:28,lv3:44,lv4:60}, r:'uncommon', lure:'软饵'},
{id:'triggerfish_titan', name:'泰坦炮弹鱼', en:'Titan Triggerfish', cat:'salt', icon:'🐡', t:{lv2:35,lv3:52,lv4:70}, r:'uncommon', lure:'软蟹/底层'},
{id:'triggerfish_clown', name:'小丑炮弹鱼', en:'Clown Triggerfish', cat:'salt', icon:'🤡', t:{lv2:30,lv3:45,lv4:60}, r:'rare', lure:'软蟹'},
{id:'trevally_silver', name:'银鲹', en:'Silver Trevally', cat:'salt', icon:'🥈', t:{lv2:28,lv3:42,lv4:58}, r:'common', lure:'小铁板'},
{id:'needlefish_keel', name:'有棱圆颌针鱼', en:'Keel-jawed Needlefish', cat:'salt', icon:'🗡', t:{lv2:30,lv3:45,lv4:60}, r:'common', lure:'表层细长路亚'},
// --- sea 远洋/深海 ---
{id:'pacific_sailfish', name:'太平洋旗鱼', en:'Pacific Sailfish', cat:'sea', icon:'⛵', t:{lv2:150,lv3:220,lv4:300}, r:'epic', lure:'拖钓/长铗饵'},
{id:'striped_marlin', name:'条纹马林鱼', en:'Striped Marlin', cat:'sea', icon:'🗡', t:{lv2:180,lv3:260,lv4:350}, r:'epic', lure:'拖钓/软饵'},
{id:'shortbill_spearfish', name:'短吻枪鱼', en:'Shortbill Spearfish', cat:'sea', icon:'🗡', t:{lv2:130,lv3:190,lv4:250}, r:'rare', lure:'拖钓'},
{id:'longbill_spearfish', name:'长吻枪鱼', en:'Longbill Spearfish', cat:'sea', icon:'🗡', t:{lv2:140,lv3:200,lv4:270}, r:'rare', lure:'拖钓'},
{id:'indo_pacific_marlin', name:'印太马林鱼', en:'Indo-Pacific Blue Marlin', cat:'sea', icon:'🗡', t:{lv2:200,lv3:300,lv4:420}, r:'legendary', lure:'大型拖钓'},
{id:'atlantic_sailfish', name:'大西洋旗鱼', en:'Atlantic Sailfish', cat:'sea', icon:'⛵', t:{lv2:150,lv3:220,lv4:300}, r:'epic', lure:'拖钓/轻铗'},
{id:'swordfish_sea', name:'剑鱼(远洋)', en:'Swordfish', cat:'sea', icon:'⚔', t:{lv2:180,lv3:280,lv4:400}, r:'legendary', lure:'深水夜钓拖钓'},
{id:'bigeye_tuna_sea', name:'大眼金枪鱼', en:'Bigeye Tuna', cat:'sea', icon:'🐟', t:{lv2:100,lv3:160,lv4:220}, r:'epic', lure:'深水铁板/拖钓'},
{id:'southern_bluefin', name:'南方蓝鳍金枪鱼', en:'Southern Bluefin Tuna', cat:'sea', icon:'🐟', t:{lv2:120,lv3:185,lv4:250}, r:'legendary', lure:'大型铁板/拖钓'},
{id:'atlantic_bluefin', name:'大西洋蓝鳍金枪鱼', en:'Atlantic Bluefin Tuna', cat:'sea', icon:'🐟', t:{lv2:150,lv3:230,lv4:330}, r:'legendary', lure:'大型拖钓/铁板'},
{id:'pacific_bluefin', name:'太平洋蓝鳍金枪鱼', en:'Pacific Bluefin Tuna', cat:'sea', icon:'🐟', t:{lv2:130,lv3:200,lv4:290}, r:'legendary', lure:'大型铁板/拖钓'},
{id:'yellowfin_tuna_sea', name:'黄鳍金枪鱼(远洋)', en:'Yellowfin Tuna (Offshore)', cat:'sea', icon:'🐟', t:{lv2:90,lv3:145,lv4:200}, r:'epic', lure:'铁板/拖钓'},
{id:'frigate_tuna', name:'圆舵鲣', en:'Frigate Tuna', cat:'sea', icon:'🐟', t:{lv2:30,lv3:45,lv4:60}, r:'common', lure:'快速铁板'},
{id:'bullet_tuna', name:'子弹金枪', en:'Bullet Tuna', cat:'sea', icon:'🐟', t:{lv2:35,lv3:52,lv4:70}, r:'common', lure:'小铁板/羽毛'},
{id:'kawakawa', name:'圆腹鲣', en:'Kawakawa', cat:'sea', icon:'🐟', t:{lv2:40,lv3:60,lv4:80}, r:'common', lure:'铁板'},
{id:'dogtooth_tuna_sea', name:'犬齿金枪鱼(远洋)', en:'Dogtooth Tuna (Offshore)', cat:'sea', icon:'🦷', t:{lv2:80,lv3:130,lv4:185}, r:'epic', lure:'深水铁板'},
{id:'little_tunny', name:'小鲔', en:'Little Tunny (False Albacore)', cat:'sea', icon:'🐟', t:{lv2:45,lv3:68,lv4:92}, r:'common', lure:'铁板/羽毛'},
{id:'wahoo_deep', name:'白甘(深水)', en:'Wahoo (Deepwater)', cat:'sea', icon:'🐟', t:{lv2:80,lv3:130,lv4:180}, r:'epic', lure:'深水快速铁板'},
{id:'mahi_mahi', name:'鬼头刀', en:'Mahi-Mahi (Dorado)', cat:'sea', icon:'🌈', t:{lv2:60,lv3:95,lv4:130}, r:'uncommon', lure:'拖钓/铁板'},
{id:'greater_amberjack_sea', name:'大俊鲹', en:'Greater Amberjack (Offshore)', cat:'sea', icon:'🐟', t:{lv2:70,lv3:110,lv4:155}, r:'rare', lure:'深水大铁板'},
{id:'almaco_jack', name:'珍鲹', en:'Almaco Jack', cat:'sea', icon:'🐟', t:{lv2:60,lv3:95,lv4:130}, r:'rare', lure:'深水铁板'},
{id:'amberjack_banded', name:'横带俊鲹', en:'Banded Rudderfish', cat:'sea', icon:'🐟', t:{lv2:50,lv3:80,lv4:110}, r:'uncommon', lure:'铁板'},
{id:'cobia_sea', name:'海鲡(远洋)', en:'Cobia (Offshore)', cat:'sea', icon:'🐟', t:{lv2:70,lv3:110,lv4:155}, r:'rare', lure:'大型软饵/铁板'},
{id:'mako_shortfin', name:'短鳍灰鲭鲨', en:'Shortfin Mako Shark', cat:'sea', icon:'🦈', t:{lv2:150,lv3:240,lv4:340}, r:'legendary', lure:'大型拖钓'},
{id:'thresher_shark', name:'长尾鲨', en:'Thresher Shark', cat:'sea', icon:'🦈', t:{lv2:200,lv3:300,lv4:420}, r:'legendary', lure:'大型拖钓'},
{id:'blue_shark', name:'蓝鲨', en:'Blue Shark', cat:'sea', icon:'🦈', t:{lv2:150,lv3:240,lv4:340}, r:'rare', lure:'拖钓'},
{id:'hammerhead', name:'双髻鲨', en:'Hammerhead Shark', cat:'sea', icon:'🔨', t:{lv2:180,lv3:280,lv4:400}, r:'legendary', lure:'大型拖钓'},
{id:'tiger_shark', name:'虎鲨', en:'Tiger Shark', cat:'sea', icon:'🦈', t:{lv2:200,lv3:320,lv4:450}, r:'legendary', lure:'大型拖钓'},
{id:'bull_shark', name:'公牛鲨', en:'Bull Shark', cat:'sea', icon:'🦈', t:{lv2:180,lv3:270,lv4:380}, r:'legendary', lure:'大型软饵/拖钓'},
{id:'silky_shark', name:'丝鲨', en:'Silky Shark', cat:'sea', icon:'🦈', t:{lv2:150,lv3:230,lv4:320}, r:'rare', lure:'拖钓'},
{id:'oceanic_whitetip', name:'远洋白鳍鲨', en:'Oceanic Whitetip Shark', cat:'sea', icon:'🦈', t:{lv2:150,lv3:230,lv4:320}, r:'rare', lure:'拖钓'},
{id:'dusky_shark', name:'铅色鲨', en:'Dusky Shark', cat:'sea', icon:'🦈', t:{lv2:160,lv3:250,lv4:360}, r:'rare', lure:'大型拖钓'},
{id:'wahoo_atlantic', name:'大西洋白甘', en:'Atlantic Wahoo', cat:'sea', icon:'🐟', t:{lv2:80,lv3:130,lv4:180}, r:'epic', lure:'快速铁板'},
{id:'rainbow_runner_sea', name:'长鲹(远洋)', en:'Rainbow Runner (Offshore)', cat:'sea', icon:'🌈', t:{lv2:55,lv3:85,lv4:115}, r:'uncommon', lure:'铁板/拖钓'},
{id:'pilot_fish', name:'领航鱼', en:'Pilot Fish', cat:'sea', icon:'🐠', t:{lv2:30,lv3:45,lv4:60}, r:'rare', lure:'随大型鱼'},
{id:'opah', name:'月鱼', en:'Opah (Moonfish)', cat:'sea', icon:'🌙', t:{lv2:80,lv3:130,lv4:180}, r:'epic', lure:'深水铁板'},
{id:'escolar', name:'软刺鲅', en:'Escolar', cat:'sea', icon:'🐟', t:{lv2:80,lv3:130,lv4:180}, r:'rare', lure:'深水拖钓'},
{id:'oilfish', name:'棘鳞蛇鲭', en:'Oilfish', cat:'sea', icon:'🐟', t:{lv2:100,lv3:160,lv4:220}, r:'rare', lure:'深水拖钓'},
{id:'wahoo_pacific3', name:'夏威夷白甘', en:'Hawaii Wahoo', cat:'sea', icon:'🐟', t:{lv2:80,lv3:125,lv4:170}, r:'epic', lure:'快速铁板'},
{id:'king_salmon_sea', name:'帝王鲑(海钓)', en:'King Salmon (Sea)', cat:'sea', icon:'🐟', t:{lv2:70,lv3:110,lv4:155}, r:'epic', lure:'大型旋转片/铁板'},
{id:'coho_sea', name:'银鲑(海钓)', en:'Coho Salmon (Sea)', cat:'sea', icon:'🐟', t:{lv2:55,lv3:85,lv4:115}, r:'uncommon', lure:'旋转片/铁板'},
{id:'atlantic_salmon_sea', name:'大西洋鲑(海钓)', en:'Atlantic Salmon (Sea)', cat:'sea', icon:'🐟', t:{lv2:60,lv3:95,lv4:130}, r:'rare', lure:'飞蝇/铁板'},
{id:'albacore_sea', name:'长鳍金枪鱼', en:'Albacore Tuna', cat:'sea', icon:'🐟', t:{lv2:60,lv3:92,lv4:125}, r:'uncommon', lure:'铁板/拖钓'},
{id:'skipjack_sea', name:'鲣鱼(远洋)', en:'Skipjack Tuna (Offshore)', cat:'sea', icon:'🐟', t:{lv2:50,lv3:75,lv4:100}, r:'common', lure:'快速铁板/拖钓'},
{id:'lancetfish', name:'帆蜥鱼', en:'Lancetfish', cat:'sea', icon:'🗡', t:{lv2:80,lv3:130,lv4:180}, r:'rare', lure:'深水拖钓'},
{id:'oarfish', name:'皇带鱼', en:'Oarfish (Regalecus)', cat:'sea', icon:'🐍', t:{lv2:300,lv3:500,lv4:800}, r:'legendary', lure:'极深水/传说'},
{id:'sunfish_mola', name:'翻车鱼', en:'Ocean Sunfish (Mola Mola)', cat:'sea', icon:'🌞', t:{lv2:100,lv3:180,lv4:280}, r:'legendary', lure:'偶尔拖钓误钓'},
{id:'tarpon_atlantic_sea', name:'大海鲢(远洋)', en:'Atlantic Tarpon (Offshore)', cat:'sea', icon:'🐟', t:{lv2:100,lv3:160,lv4:220}, r:'epic', lure:'大型软饵/铁板'},
{id:'amberjack_almaco_sea', name:'深水鲹王', en:'Almaco Jack (Deep)', cat:'sea', icon:'🐟', t:{lv2:65,lv3:100,lv4:140}, r:'rare', lure:'深水铁板'},
{id:'yellowfin_grouper', name:'黄鳍石斑(深海)', en:'Yellowfin Grouper (Deep)', cat:'sea', icon:'🐡', t:{lv2:45,lv3:70,lv4:95}, r:'rare', lure:'深水铁板'},
{id:'misty_grouper', name:'暗棕石斑', en:'Misty Grouper', cat:'sea', icon:'🐡', t:{lv2:50,lv3:80,lv4:115}, r:'epic', lure:'深水铁板'},
{id:'warsaw_grouper', name:'华沙石斑', en:'Warsaw Grouper', cat:'sea', icon:'🐡', t:{lv2:80,lv3:130,lv4:185}, r:'epic', lure:'深水大铁板'},
{id:'snowy_grouper', name:'雪花石斑', en:'Snowy Grouper', cat:'sea', icon:'🐡', t:{lv2:55,lv3:88,lv4:120}, r:'rare', lure:'深水铁板'},
{id:'hapuku', name:'哈帕库石斑(新西兰)', en:'Hapuku Grouper', cat:'sea', icon:'🐡', t:{lv2:60,lv3:95,lv4:130}, r:'epic', lure:'深水铁板'},
{id:'bass_chilean', name:'智利鲈', en:'Chilean Sea Bass (Patagonian Toothfish)', cat:'sea', icon:'🐟', t:{lv2:80,lv3:130,lv4:180}, r:'legendary', lure:'深水拖钓'},
{id:'orange_roughy', name:'橙棘鲷', en:'Orange Roughy', cat:'sea', icon:'🟠', t:{lv2:30,lv3:45,lv4:60}, r:'epic', lure:'超深水铁板'},
{id:'alfonsino', name:'金眼鲷', en:'Alfonsino', cat:'sea', icon:'🔴', t:{lv2:30,lv3:45,lv4:60}, r:'rare', lure:'深水铁板'},
{id:'bluenose_warehou', name:'蓝鼻鱼', en:'Bluenose Warehou', cat:'sea', icon:'🔵', t:{lv2:40,lv3:65,lv4:90}, r:'rare', lure:'深水铁板'},
{id:'gemfish', name:'宝石鱼', en:'Gemfish (Hake)', cat:'sea', icon:'💎', t:{lv2:55,lv3:88,lv4:120}, r:'rare', lure:'深水拖钓'},
{id:'lingcod', name:'格陵兰鳕(北美)', en:'Lingcod', cat:'sea', icon:'🐟', t:{lv2:55,lv3:88,lv4:120}, r:'uncommon', lure:'深水软鱼'},
{id:'black_rockfish', name:'黑岩鱼', en:'Black Rockfish', cat:'sea', icon:'🐟', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'岩礁软虫'},
{id:'copper_rockfish', name:'铜岩鱼', en:'Copper Rockfish', cat:'sea', icon:'🟤', t:{lv2:35,lv3:55,lv4:75}, r:'uncommon', lure:'岩礁铁板'},
{id:'canary_rockfish', name:'金丝雀岩鱼', en:'Canary Rockfish', cat:'sea', icon:'🟡', t:{lv2:35,lv3:55,lv4:75}, r:'rare', lure:'深水铁板'},
{id:'yelloweye_rockfish', name:'黄眼岩鱼', en:'Yelloweye Rockfish', cat:'sea', icon:'🔴', t:{lv2:45,lv3:70,lv4:95}, r:'epic', lure:'超深水铁板'},
{id:'tiger_rockfish', name:'虎纹岩鱼', en:'Tiger Rockfish', cat:'sea', icon:'🐯', t:{lv2:40,lv3:62,lv4:85}, r:'rare', lure:'深水软虫'},
{id:'quillback_rockfish', name:'笔形岩鱼', en:'Quillback Rockfish', cat:'sea', icon:'🐟', t:{lv2:38,lv3:58,lv4:78}, r:'uncommon', lure:'岩礁软饵'},
{id:'bocaccio', name:'博卡喷射鱼', en:'Bocaccio', cat:'sea', icon:'🐟', t:{lv2:45,lv3:70,lv4:95}, r:'rare', lure:'深水铁板'},
{id:'northern_pacific_halibut', name:'太平洋比目鱼', en:'Pacific Halibut', cat:'sea', icon:'🫓', t:{lv2:80,lv3:150,lv4:250}, r:'epic', lure:'大型软鱼底拖'},
{id:'greenland_halibut', name:'格陵兰比目鱼', en:'Greenland Halibut', cat:'sea', icon:'🫓', t:{lv2:60,lv3:100,lv4:145}, r:'rare', lure:'深水拖钓'},
{id:'atlantic_halibut', name:'大西洋比目鱼', en:'Atlantic Halibut', cat:'sea', icon:'🫓', t:{lv2:100,lv3:180,lv4:280}, r:'legendary', lure:'深水大型软饵'},
{id:'atlantic_cod', name:'大西洋鳕鱼', en:'Atlantic Cod', cat:'sea', icon:'🐟', t:{lv2:50,lv3:80,lv4:115}, r:'uncommon', lure:'铁板/底层软饵'},
{id:'pollock_atlantic', name:'大西洋狭鳕', en:'Pollock', cat:'sea', icon:'🐟', t:{lv2:45,lv3:70,lv4:95}, r:'common', lure:'铁板'},
{id:'pacific_cod', name:'太平洋鳕', en:'Pacific Cod', cat:'sea', icon:'🐟', t:{lv2:55,lv3:88,lv4:120}, r:'uncommon', lure:'底层铁板'},
{id:'haddock', name:'黑线鳕', en:'Haddock', cat:'sea', icon:'🐟', t:{lv2:40,lv3:62,lv4:85}, r:'uncommon', lure:'底层铁板'},
{id:'whiting_eu', name:'欧洲无须鳕', en:'European Whiting', cat:'sea', icon:'🐟', t:{lv2:30,lv3:45,lv4:60}, r:'common', lure:'小铁板'},
{id:'blue_ling', name:'蓝长鳕', en:'Blue Ling', cat:'sea', icon:'🔵', t:{lv2:60,lv3:95,lv4:130}, r:'rare', lure:'深水铁板'},
{id:'conger_eel', name:'海鳗', en:'Conger Eel', cat:'sea', icon:'🐍', t:{lv2:80,lv3:130,lv4:180}, r:'rare', lure:'夜钓深水软饵'},
{id:'moray_eel', name:'海鳝', en:'Moray Eel', cat:'sea', icon:'🐍', t:{lv2:60,lv3:100,lv4:150}, r:'uncommon', lure:'底层活饵仿生'},
{id:'giant_moray', name:'巨型海鳝', en:'Giant Moray Eel', cat:'sea', icon:'🐍', t:{lv2:120,lv3:200,lv4:280}, r:'epic', lure:'大型软饵夜钓'},
{id:'school_shark', name:'锥齿鲨', en:'School Shark', cat:'sea', icon:'🦈', t:{lv2:100,lv3:160,lv4:220}, r:'uncommon', lure:'拖钓'},
{id:'porbeagle', name:'鼠鲨', en:'Porbeagle Shark', cat:'sea', icon:'🦈', t:{lv2:140,lv3:220,lv4:310}, r:'rare', lure:'拖钓'},
{id:'spiny_dogfish', name:'星鲨', en:'Spiny Dogfish', cat:'sea', icon:'🦈', t:{lv2:55,lv3:85,lv4:115}, r:'common', lure:'底层软饵'},
{id:'smooth_hound', name:'鲎头犁齿鲨', en:'Smooth Hound', cat:'sea', icon:'🦈', t:{lv2:60,lv3:95,lv4:130}, r:'common', lure:'底层软蟹'},
{id:'lemon_shark', name:'柠檬鲨', en:'Lemon Shark', cat:'sea', icon:'🍋', t:{lv2:140,lv3:220,lv4:310}, r:'rare', lure:'大型软饵'},
{id:'broadbill_swordfish', name:'宽嘴剑鱼', en:'Broadbill Swordfish', cat:'sea', icon:'⚔', t:{lv2:200,lv3:310,lv4:450}, r:'legendary', lure:'深水夜钓大型软饵'},
