// 补充批次 - 凑齐500种
const FISH_DB_EXTRA2 = [
// ===== 淡水补充（北美/欧洲/非洲/澳洲特色）=====
{id:'striped_bass',name:'条纹鲈',en:'Striped Bass',cat:'fresh',icon:'🎯',t:{lv2:55,lv3:80,lv4:100},r:'rare',lure:'大型米诺、铁板'},
{id:'white_bass',name:'白鲈',en:'White Bass',cat:'fresh',icon:'⬜',t:{lv2:25,lv3:38,lv4:50},r:'common',lure:'旋转饵、铁板'},
{id:'hybrid_striped_bass',name:'杂交条纹鲈',en:'Hybrid Striped Bass',cat:'fresh',icon:'🔀',t:{lv2:40,lv3:60,lv4:80},r:'uncommon',lure:'旋转饵、铁板'},
{id:'alligator_gar',name:'大鳄雀鳝',en:'Alligator Gar',cat:'fresh',icon:'🐊',t:{lv2:120,lv3:180,lv4:250},r:'legendary',lure:'大型路亚、切克客'},
{id:'longnose_gar',name:'长鼻雀鳝',en:'Longnose Gar',cat:'fresh',icon:'🔫',t:{lv2:60,lv3:90,lv4:120},r:'rare',lure:'绳状路亚'},
{id:'shortnose_gar',name:'短鼻雀鳝',en:'Shortnose Gar',cat:'fresh',icon:'🗡️',t:{lv2:40,lv3:60,lv4:80},r:'uncommon',lure:'米诺、旋转饵'},
{id:'bowfin',name:'弓鳍鱼',en:'Bowfin',cat:'fresh',icon:'🏹',t:{lv2:45,lv3:65,lv4:85},r:'uncommon',lure:'软虫、旋转饵'},
{id:'american_eel',name:'美洲鳗鲡',en:'American Eel',cat:'fresh',icon:'〰️',t:{lv2:50,lv3:80,lv4:110},r:'uncommon',lure:'小型铁板、软虫'},
{id:'european_eel',name:'欧洲鳗鲡',en:'European Eel',cat:'fresh',icon:'〰️',t:{lv2:55,lv3:85,lv4:120},r:'rare',lure:'软虫、小铁板'},
{id:'japanese_eel',name:'日本鳗鲡',en:'Japanese Eel',cat:'fresh',icon:'🐍',t:{lv2:50,lv3:75,lv4:100},r:'rare',lure:'软虫底钓'},
{id:'lake_trout',name:'湖鳟',en:'Lake Trout',cat:'fresh',icon:'🏔️',t:{lv2:50,lv3:75,lv4:100},r:'rare',lure:'深水铁板、旋转饵'},
{id:'brook_trout',name:'溪红点鲑',en:'Brook Trout',cat:'fresh',icon:'🌿',t:{lv2:25,lv3:38,lv4:50},r:'uncommon',lure:'飞蝇、旋转饵'},
{id:'sockeye_salmon',name:'红鲑',en:'Sockeye Salmon',cat:'fresh',icon:'🔴',t:{lv2:45,lv3:65,lv4:80},r:'rare',lure:'旋转饵、飞蝇'},
{id:'coho_salmon',name:'银鲑',en:'Coho Salmon',cat:'fresh',icon:'🥈',t:{lv2:55,lv3:80,lv4:100},r:'rare',lure:'旋转饵、米诺'},
{id:'chum_salmon',name:'马苏鲑',en:'Chum Salmon',cat:'fresh',icon:'🍁',t:{lv2:50,lv3:75,lv4:95},r:'rare',lure:'旋转饵、飞蝇'},
{id:'pink_salmon',name:'粉红鲑',en:'Pink Salmon',cat:'fresh',icon:'🌸',t:{lv2:40,lv3:58,lv4:75},r:'uncommon',lure:'旋转饵、小铁板'},
{id:'arctic_grayling',name:'北极茴鱼',en:'Arctic Grayling',cat:'fresh',icon:'❄️',t:{lv2:30,lv3:45,lv4:60},r:'rare',lure:'飞蝇、超轻路亚'},
{id:'whitefish_lake',name:'湖白鲑',en:'Lake Whitefish',cat:'fresh',icon:'🤍',t:{lv2:35,lv3:52,lv4:68},r:'uncommon',lure:'小铁板、飞蝇'},
{id:'cisco',name:'北美白鲑',en:'Cisco',cat:'fresh',icon:'💫',t:{lv2:28,lv3:42,lv4:55},r:'common',lure:'小铁板、旋转饵'},
{id:'yellow_perch',name:'北美黄鲈',en:'Yellow Perch',cat:'fresh',icon:'🟡',t:{lv2:20,lv3:30,lv4:40},r:'common',lure:'小软虫、超轻铁板'},
{id:'sauger',name:'细鳞梭鲈',en:'Sauger',cat:'fresh',icon:'🔍',t:{lv2:30,lv3:45,lv4:60},r:'uncommon',lure:'软虫、铁板'},
{id:'freshwater_drum',name:'淡水石首鱼',en:'Freshwater Drum',cat:'fresh',icon:'🥁',t:{lv2:40,lv3:60,lv4:80},r:'common',lure:'软虫、铁板'},
{id:'white_crappie',name:'白莓鲈',en:'White Crappie',cat:'fresh',icon:'⚪',t:{lv2:22,lv3:32,lv4:42},r:'common',lure:'微型软虫、小铁板'},
{id:'longear_sunfish',name:'长耳太阳鱼',en:'Longear Sunfish',cat:'fresh',icon:'☀️',t:{lv2:12,lv3:18,lv4:25},r:'common',lure:'超轻飞蝇、小旋转饵'},
{id:'redear_sunfish',name:'红耳太阳鱼',en:'Redear Sunfish',cat:'fresh',icon:'🌺',t:{lv2:18,lv3:28,lv4:38},r:'common',lure:'超轻路亚、飞蝇'},
{id:'warmouth',name:'阔嘴太阳鱼',en:'Warmouth',cat:'fresh',icon:'😤',t:{lv2:15,lv3:22,lv4:30},r:'common',lure:'小软虫、飞蝇'},
{id:'rock_bass',name:'岩鲈',en:'Rock Bass',cat:'fresh',icon:'🪨',t:{lv2:18,lv3:27,lv4:35},r:'common',lure:'小软虫、旋转饵'},
{id:'flier',name:'飞鲈',en:'Flier',cat:'fresh',icon:'✈️',t:{lv2:12,lv3:18,lv4:24},r:'common',lure:'小型软饵'},
{id:'blue_catfish',name:'蓝鲶',en:'Blue Catfish',cat:'fresh',icon:'🔵',t:{lv2:60,lv3:90,lv4:130},r:'epic',lure:'大型软饵、切克客'},
{id:'channel_catfish',name:'斑点叉尾鮰',en:'Channel Catfish',cat:'fresh',icon:'🐠',t:{lv2:45,lv3:65,lv4:85},r:'common',lure:'软饵、旋转饵'},
{id:'flathead_catfish',name:'平头鲶',en:'Flathead Catfish',cat:'fresh',icon:'🪓',t:{lv2:65,lv3:100,lv4:140},r:'epic',lure:'大型活饵软饵'},
{id:'bullhead_catfish',name:'牛头鲶',en:'Bullhead Catfish',cat:'fresh',icon:'🐮',t:{lv2:25,lv3:38,lv4:50},r:'common',lure:'底层软饵'},
{id:'carp_common',name:'鲤鱼',en:'Common Carp',cat:'fresh',icon:'🎏',t:{lv2:45,lv3:70,lv4:95},r:'common',lure:'软饵、仿生玉米'},
{id:'carp_mirror',name:'镜鲤',en:'Mirror Carp',cat:'fresh',icon:'🪞',t:{lv2:50,lv3:78,lv4:105},r:'uncommon',lure:'软饵、发酵饵'},
{id:'bighead_carp',name:'鳙鱼',en:'Bighead Carp',cat:'fresh',icon:'🐡',t:{lv2:50,lv3:80,lv4:110},r:'common',lure:'大型铁板'},
{id:'silver_carp',name:'鲢鱼',en:'Silver Carp',cat:'fresh',icon:'🐟',t:{lv2:45,lv3:70,lv4:95},r:'common',lure:'铁板'},
{id:'ide_fish',name:'鲤属白鱼',en:'Ide',cat:'fresh',icon:'🌊',t:{lv2:35,lv3:55,lv4:72},r:'uncommon',lure:'旋转饵、米诺'},
{id:'chub_european',name:'欧洲铜鱼',en:'European Chub',cat:'fresh',icon:'🟤',t:{lv2:30,lv3:45,lv4:60},r:'uncommon',lure:'旋转饵、小米诺'},
{id:'roach',name:'欧鳊',en:'Roach',cat:'fresh',icon:'🔘',t:{lv2:20,lv3:30,lv4:40},r:'common',lure:'超轻路亚'},
{id:'rudd',name:'红眼鲌',en:'Rudd',cat:'fresh',icon:'🔴',t:{lv2:22,lv3:33,lv4:44},r:'common',lure:'超轻路亚、飞蝇'},
{id:'bream_european',name:'欧洲鳊',en:'European Bream',cat:'fresh',icon:'🫓',t:{lv2:30,lv3:48,lv4:65},r:'common',lure:'软饵'},
{id:'tench',name:'丁鱥',en:'Tench',cat:'fresh',icon:'🟢',t:{lv2:35,lv3:55,lv4:70},r:'uncommon',lure:'软饵底钓'},
{id:'barbel',name:'鲃鱼',en:'Barbel',cat:'fresh',icon:'🎋',t:{lv2:45,lv3:68,lv4:90},r:'uncommon',lure:'旋转饵、底层软饵'},
{id:'burbot',name:'江鳕',en:'Burbot',cat:'fresh',icon:'🌑',t:{lv2:40,lv3:62,lv4:85},r:'rare',lure:'发光铁板、小铁板'},
{id:'perch_nile',name:'尼罗河鲈二代',en:'Nile Tilapia',cat:'fresh',icon:'🌍',t:{lv2:30,lv3:45,lv4:60},r:'common',lure:'软虫、小型路亚'},
{id:'tigerfish_small',name:'条纹猛鱼',en:'Banded Tigerfish',cat:'fresh',icon:'🐯',t:{lv2:30,lv3:48,lv4:65},r:'rare',lure:'亮片、旋转饵'},
{id:'vundu_catfish',name:'万杜鲶',en:'Vundu Catfish',cat:'fresh',icon:'🦈',t:{lv2:80,lv3:130,lv4:180},r:'epic',lure:'大型软饵'},
{id:'sharptooth_catfish',name:'锐齿鲶',en:'Sharptooth Catfish',cat:'fresh',icon:'🦷',t:{lv2:70,lv3:110,lv4:155},r:'rare',lure:'大型软饵底钓'},
{id:'african_pike',name:'非洲梭鱼',en:'African Pike',cat:'fresh',icon:'🌍',t:{lv2:40,lv3:60,lv4:80},r:'rare',lure:'米诺、旋转饵'},
{id:'leopard_bush_fish',name:'豹纹攀鲈',en:'Leopard Bush Fish',cat:'fresh',icon:'🐆',t:{lv2:12,lv3:20,lv4:28},r:'rare',lure:'超轻路亚'},
{id:'australian_bass',name:'澳洲河鲈',en:'Australian Bass',cat:'fresh',icon:'🦘',t:{lv2:30,lv3:45,lv4:60},r:'uncommon',lure:'小型米诺、软虫'},
{id:'golden_perch',name:'黄金河鲈',en:'Golden Perch',cat:'fresh',icon:'🏅',t:{lv2:35,lv3:55,lv4:75},r:'uncommon',lure:'软虫、旋转饵'},
{id:'saratoga',name:'萨拉托加龙鱼',en:'Saratoga',cat:'fresh',icon:'🐉',t:{lv2:45,lv3:70,lv4:95},r:'epic',lure:'水面饵'},
{id:'sooty_grunter',name:'黑喉叫鱼',en:'Sooty Grunter',cat:'fresh',icon:'⬛',t:{lv2:25,lv3:38,lv4:52},r:'uncommon',lure:'小型米诺、旋转饵'},
{id:'jungle_perch',name:'丛林鲈',en:'Jungle Perch',cat:'fresh',icon:'🌴',t:{lv2:20,lv3:32,lv4:45},r:'rare',lure:'小型路亚'},
{id:'mahseer_hump',name:'驼背马哈鱼',en:'Humpback Mahseer',cat:'fresh',icon:'🏋️',t:{lv2:55,lv3:85,lv4:115},r:'legendary',lure:'大型旋转饵'},
{id:'mahseer_blue',name:'蓝鳍马哈鱼',en:'Bluefin Mahseer',cat:'fresh',icon:'💙',t:{lv2:45,lv3:70,lv4:95},r:'legendary',lure:'旋转饵、米诺'},
{id:'giant_gourami',name:'丝足鲈',en:'Giant Gourami',cat:'fresh',icon:'🐟',t:{lv2:35,lv3:55,lv4:70},r:'uncommon',lure:'小型软虫'},
{id:'hampala_barb',name:'红线无须鲃',en:'Hampala Barb',cat:'fresh',icon:'🔥',t:{lv2:25,lv3:40,lv4:55},r:'uncommon',lure:'小型米诺、旋转饵'},
{id:'toman_giant',name:'巨鳢',en:'Giant Snakehead',cat:'fresh',icon:'🐲',t:{lv2:70,lv3:110,lv4:150},r:'legendary',lure:'大型雷蛙'},
{id:'sebarau',name:'西里伯斯鲈',en:'Sebarau',cat:'fresh',icon:'🏝️',t:{lv2:35,lv3:55,lv4:72},r:'rare',lure:'米诺、软虫'},
{id:'temensis_peacock',name:'巨型三间孔雀鲈',en:'Speckled Peacock Bass',cat:'fresh',icon:'🏆',t:{lv2:50,lv3:75,lv4:100},r:'legendary',lure:'波扒、大型米诺'},
{id:'ocellaris_peacock',name:'皇冠三间',en:'Butterfly Peacock Bass',cat:'fresh',icon:'🦋',t:{lv2:30,lv3:48,lv4:65},r:'epic',lure:'水面路亚、米诺'},
{id:'red_bellied_piranha',name:'红腹食人鱼',en:'Red-bellied Piranha',cat:'fresh',icon:'🩸',t:{lv2:20,lv3:28,lv4:38},r:'epic',lure:'金属亮片'},
{id:'pacu',name:'巨脂鲤',en:'Pacu',cat:'fresh',icon:'🦷',t:{lv2:45,lv3:68,lv4:90},r:'rare',lure:'果实型饵'},
{id:'colossoma',name:'科罗索马鱼',en:'Colossoma',cat:'fresh',icon:'🌳',t:{lv2:50,lv3:75,lv4:100},r:'rare',lure:'大型软饵'},
{id:'matrinxa',name:'马特林萨脂鲤',en:'Matrinxa',cat:'fresh',icon:'⚡',t:{lv2:40,lv3:62,lv4:82},r:'epic',lure:'水面饵、米诺'},
{id:'payara_dracula',name:'吸血鬼鱼',en:'Dracula Fish/Payara',cat:'fresh',icon:'🧛',t:{lv2:55,lv3:82,lv4:110},r:'legendary',lure:'大型米诺（需钢丝导线）'},
{id:'bicuda',name:'南美梭鱼',en:'Bicuda',cat:'fresh',icon:'🏹',t:{lv2:45,lv3:70,lv4:95},r:'epic',lure:'细长铁板、米诺'},
{id:'trahira',name:'特拉希拉牙鱼',en:'Trahira',cat:'fresh',icon:'🐊',t:{lv2:35,lv3:55,lv4:75},r:'rare',lure:'软饵、亮片'},
{id:'giant_catfish_mekong',name:'湄公河巨鲶',en:'Mekong Giant Catfish',cat:'fresh',icon:'🦕',t:{lv2:150,lv3:220,lv4:300},r:'legendary',lure:'大型软饵'},
{id:'mahseer_tor',name:'托氏马哈鱼',en:'Tor Mahseer',cat:'fresh',icon:'🌊',t:{lv2:55,lv3:85,lv4:115},r:'legendary',lure:'大型旋转饵'},
{id:'siamese_carp',name:'暹罗巨鲤',en:'Siamese Giant Carp',cat:'fresh',icon:'🎆',t:{lv2:100,lv3:160,lv4:220},r:'legendary',lure:'大型软饵'},
{id:'striped_snakehead',name:'线鳢',en:'Striped Snakehead',cat:'fresh',icon:'➿',t:{lv2:35,lv3:55,lv4:75},r:'uncommon',lure:'雷蛙、软虫'},
{id:'red_tail_catfish',name:'红尾鲶',en:'Red-tailed Catfish',cat:'fresh',icon:'🔴',t:{lv2:80,lv3:130,lv4:180},r:'epic',lure:'大型软饵'},
{id:'tiger_shovelnose',name:'虎纹铲吻鲶',en:'Tiger Shovelnose Catfish',cat:'fresh',icon:'🐯',t:{lv2:80,lv3:120,lv4:160},r:'epic',lure:'大型软饵'},
{id:'sorubim',name:'南美铲吻鲶',en:'Sorubim',cat:'fresh',icon:'🛶',t:{lv2:60,lv3:90,lv4:120},r:'rare',lure:'底层软饵'},
{id:'ripsaw_catfish',name:'锯齿鲶',en:'Ripsaw Catfish',cat:'fresh',icon:'🔪',t:{lv2:55,lv3:82,lv4:110},r:'rare',lure:'大型软饵'},
{id:'piraiba',name:'皮来巴巨鲶',en:'Piraiba',cat:'fresh',icon:'🌊',t:{lv2:150,lv3:230,lv4:320},r:'legendary',lure:'大型软饵'},
{id:'wels_catfish',name:'欧洲巨鲶',en:'Wels Catfish',cat:'fresh',icon:'🐳',t:{lv2:120,lv3:200,lv4:280},r:'legendary',lure:'大型软饵、切克客'},
{id:'pike_perch',name:'梭鲈',en:'Pike-Perch',cat:'fresh',icon:'🎯',t:{lv2:45,lv3:68,lv4:90},r:'uncommon',lure:'软虫、小铁板'},
{id:'huchen',name:'多瑙河鲑',en:'Huchen',cat:'fresh',icon:'🏞️',t:{lv2:70,lv3:105,lv4:140},r:'legendary',lure:'大型米诺、旋转饵'},
{id:'giant_pike',name:'欧洲大白斑狗鱼',en:'Giant Pike',cat:'fresh',icon:'🗡️',t:{lv2:80,lv3:120,lv4:155},r:'legendary',lure:'大型亮片、大米诺'},
{id:'asp_fish',name:'欧洲拟鲤',en:'Asp',cat:'fresh',icon:'⚔️',t:{lv2:45,lv3:68,lv4:88},r:'rare',lure:'铁板、亮片'},
{id:'perch_balkhash',name:'巴尔喀什鲈',en:'Balkhash Perch',cat:'fresh',icon:'🏔️',t:{lv2:30,lv3:45,lv4:60},r:'rare',lure:'小铁板、软虫'},
{id:'aral_barbel',name:'咸海鲃',en:'Aral Barbel',cat:'fresh',icon:'🌵',t:{lv2:35,lv3:55,lv4:72},r:'rare',lure:'底层软饵'},
{id:'amur_pike',name:'黑斑狗鱼',en:'Amur Pike',cat:'fresh',icon:'🌑',t:{lv2:55,lv3:82,lv4:108},r:'rare',lure:'大型米诺'},
{id:'amur_catfish',name:'鲿鱼',en:'Amur Catfish',cat:'fresh',icon:'🐟',t:{lv2:35,lv3:55,lv4:75},r:'uncommon',lure:'软虫底钓'},
{id:'lenok',name:'细鳞鱼',en:'Lenok',cat:'fresh',icon:'🏔️',t:{lv2:35,lv3:55,lv4:72},r:'rare',lure:'飞蝇、小旋转饵'},
{id:'grayling_mongolian',name:'蒙古茴鱼',en:'Mongolian Grayling',cat:'fresh',icon:'🌿',t:{lv2:30,lv3:45,lv4:60},r:'rare',lure:'飞蝇'},
{id:'taimen_sakhalin',name:'远东哲罗鲑',en:'Sakhalin Taimen',cat:'fresh',icon:'🌸',t:{lv2:80,lv3:120,lv4:160},r:'legendary',lure:'大型水面饵、米诺'},
{id:'ito_taimen',name:'伊藤哲罗鲑',en:'Ito Taimen',cat:'fresh',icon:'⛩️',t:{lv2:75,lv3:110,lv4:150},r:'legendary',lure:'大型米诺'},

// ===== 近岸海水路亚补充（salt）=====
{id:'roosterfish',name:'公鸡鱼',en:'Roosterfish',cat:'salt',icon:'🐓',t:{lv2:70,lv3:110,lv4:150},r:'legendary',lure:'大型波扒、铅笔'},
{id:'permit',name:'许氏平鲉',en:'Permit',cat:'salt',icon:'🥇',t:{lv2:45,lv3:68,lv4:90},r:'epic',lure:'飞蝇、软蟹饵'},
{id:'snook',name:'钝鱼',en:'Snook',cat:'salt',icon:'🎣',t:{lv2:55,lv3:80,lv4:105},r:'rare',lure:'米诺、软虫'},
{id:'black_sea_bass',name:'黑海鲈',en:'Black Sea Bass',cat:'salt',icon:'🖤',t:{lv2:25,lv3:38,lv4:50},r:'common',lure:'软虫、铁板'},
{id:'striped_marlin',name:'条纹马林',en:'Striped Marlin',cat:'salt',icon:'〰️',t:{lv2:120,lv3:200,lv4:300},r:'legendary',lure:'拖钓'},
{id:'speckled_seatrout',name:'斑点海鳟',en:'Speckled Seatrout',cat:'salt',icon:'🟤',t:{lv2:40,lv3:58,lv4:75},r:'uncommon',lure:'软虫、旋转饵'},
{id:'bluefish',name:'蓝鱼',en:'Bluefish',cat:'salt',icon:'🔵',t:{lv2:45,lv3:65,lv4:85},r:'uncommon',lure:'铁板、波扒'},
{id:'flounder_summer',name:'夏比目鱼',en:'Summer Flounder',cat:'salt',icon:'🍂',t:{lv2:45,lv3:65,lv4:85},r:'uncommon',lure:'软虫、底层铁板'},
{id:'atlantic_cod',name:'大西洋鳕鱼',en:'Atlantic Cod',cat:'salt',icon:'🐟',t:{lv2:60,lv3:90,lv4:120},r:'uncommon',lure:'铁板、软虫'},
{id:'pollock',name:'绿鳕',en:'Pollock',cat:'salt',icon:'🟢',t:{lv2:50,lv3:75,lv4:100},r:'common',lure:'铁板、旋转饵'},
{id:'lingcod',name:'岩鳕',en:'Lingcod',cat:'salt',icon:'🪨',t:{lv2:65,lv3:98,lv4:130},r:'rare',lure:'大型软虫、铁板'},
{id:'rockfish_pacific',name:'太平洋岩鱼',en:'Pacific Rockfish',cat:'salt',icon:'🪨',t:{lv2:30,lv3:48,lv4:65},r:'uncommon',lure:'软虫、铁板'},
{id:'cabrilla',name:'卡比拉石斑',en:'Cabrilla',cat:'salt',icon:'🌊',t:{lv2:35,lv3:52,lv4:70},r:'uncommon',lure:'软虫、铁板'},
{id:'california_halibut',name:'加州比目鱼',en:'California Halibut',cat:'salt',icon:'🌴',t:{lv2:60,lv3:90,lv4:120},r:'rare',lure:'软虫、铁板'},
{id:'white_seabass',name:'白海鲈',en:'White Seabass',cat:'salt',icon:'⬜',t:{lv2:60,lv3:92,lv4:125},r:'rare',lure:'米诺、软虫'},
{id:'yelloweye_rockfish',name:'黄眼岩鱼',en:'Yelloweye Rockfish',cat:'salt',icon:'👁️',t:{lv2:40,lv3:60,lv4:80},r:'rare',lure:'深场铁板'},
{id:'golden_trevally',name:'金瓜鲹',en:'Golden Trevally',cat:'salt',icon:'🥇',t:{lv2:40,lv3:62,lv4:82},r:'rare',lure:'铁板、波扒'},
{id:'bigeye_trevally',name:'大眼鲹',en:'Bigeye Trevally',cat:'salt',icon:'👀',t:{lv2:40,lv3:60,lv4:80},r:'uncommon',lure:'铁板、小波扒'},
{id:'brassy_trevally',name:'黄点鲹',en:'Brassy Trevally',cat:'salt',icon:'🔶',t:{lv2:35,lv3:55,lv4:72},r:'uncommon',lure:'铁板'},
{id:'diamond_trevally',name:'菱形鲹',en:'Diamond Trevally',cat:'salt',icon:'♦️',t:{lv2:40,lv3:60,lv4:80},r:'uncommon',lure:'铁板'},
{id:'african_pompano',name:'非洲鲳参',en:'African Pompano',cat:'salt',icon:'🌍',t:{lv2:50,lv3:75,lv4:100},r:'rare',lure:'铁板、深场路亚'},
{id:'almaco_jack',name:'阿尔马科鲹',en:'Almaco Jack',cat:'salt',icon:'🔱',t:{lv2:55,lv3:82,lv4:110},r:'rare',lure:'铁板'},
{id:'banded_rudderfish',name:'带状舵鱼',en:'Banded Rudderfish',cat:'salt',icon:'🎀',t:{lv2:35,lv3:52,lv4:70},r:'uncommon',lure:'铁板、软虫'},
{id:'pacific_amberjack',name:'太平洋章红',en:'Pacific Amberjack',cat:'salt',icon:'🌊',t:{lv2:60,lv3:90,lv4:120},r:'rare',lure:'深场铁板'},
{id:'black_grouper',name:'黑石斑',en:'Black Grouper',cat:'salt',icon:'⬛',t:{lv2:55,lv3:82,lv4:110},r:'rare',lure:'底层铁板'},
{id:'nassau_grouper',name:'拿骚石斑',en:'Nassau Grouper',cat:'salt',icon:'🏝️',t:{lv2:45,lv3:68,lv4:90},r:'epic',lure:'铁板、软虫'},
{id:'gag_grouper',name:'盖石斑',en:'Gag Grouper',cat:'salt',icon:'🎭',t:{lv2:50,lv3:75,lv4:100},r:'rare',lure:'铁板'},
{id:'scamp_grouper',name:'坎普石斑',en:'Scamp Grouper',cat:'salt',icon:'🏕️',t:{lv2:40,lv3:60,lv4:80},r:'uncommon',lure:'铁板、软虫'},
{id:'warsaw_grouper',name:'华沙石斑',en:'Warsaw Grouper',cat:'salt',icon:'🏰',t:{lv2:100,lv3:160,lv4:220},r:'legendary',lure:'超重铁板'},
{id:'tiger_grouper',name:'虎斑石斑',en:'Tiger Grouper',cat:'salt',icon:'🐯',t:{lv2:40,lv3:62,lv4:82},r:'rare',lure:'铁板'},
{id:'coral_trout',name:'珊瑚鲈',en:'Coral Trout',cat:'salt',icon:'🪸',t:{lv2:40,lv3:60,lv4:80},r:'rare',lure:'铁板、软虫'},
{id:'yellowfin_grouper',name:'黄鳍石斑',en:'Yellowfin Grouper',cat:'salt',icon:'💛',t:{lv2:45,lv3:68,lv4:90},r:'rare',lure:'铁板'},
{id:'lane_snapper',name:'车道笛鲷',en:'Lane Snapper',cat:'salt',icon:'🛣️',t:{lv2:25,lv3:38,lv4:50},r:'common',lure:'软虫、小铁板'},
{id:'mutton_snapper',name:'羊笛鲷',en:'Mutton Snapper',cat:'salt',icon:'🐑',t:{lv2:45,lv3:68,lv4:90},r:'rare',lure:'铁板、软虫'},
{id:'yellowtail_snapper',name:'黄尾笛鲷',en:'Yellowtail Snapper',cat:'salt',icon:'🟡',t:{lv2:30,lv3:45,lv4:60},r:'common',lure:'小铁板、软虫'},
{id:'dog_snapper',name:'犬牙笛鲷',en:'Dog Snapper',cat:'salt',icon:'🐕',t:{lv2:50,lv3:75,lv4:100},r:'rare',lure:'铁板'},
{id:'cubera_snapper',name:'古巴笛鲷',en:'Cubera Snapper',cat:'salt',icon:'🌊',t:{lv2:80,lv3:120,lv4:160},r:'legendary',lure:'大型铁板'},
{id:'gray_snapper',name:'灰笛鲷',en:'Gray Snapper',cat:'salt',icon:'🩶',t:{lv2:30,lv3:45,lv4:60},r:'uncommon',lure:'软虫、铁板'},
{id:'vermilion_snapper',name:'朱红笛鲷',en:'Vermilion Snapper',cat:'salt',icon:'🔴',t:{lv2:25,lv3:38,lv4:50},r:'common',lure:'软虫'},
{id:'emperor_fish',name:'龙占鱼',en:'Emperor Fish',cat:'salt',icon:'👑',t:{lv2:45,lv3:68,lv4:90},r:'rare',lure:'铁板、软虫'},
{id:'sweetlips',name:'石鲷',en:'Oriental Sweetlips',cat:'salt',icon:'💋',t:{lv2:30,lv3:45,lv4:60},r:'uncommon',lure:'软虫'},
{id:'triggerfish_titan',name:'泰坦炮弹鱼',en:'Titan Triggerfish',cat:'salt',icon:'💣',t:{lv2:40,lv3:60,lv4:75},r:'rare',lure:'铁板'},
{id:'jack_crevalle',name:'马鲹',en:'Jack Crevalle',cat:'salt',icon:'🔱',t:{lv2:45,lv3:68,lv4:90},r:'uncommon',lure:'铁板、波扒'},
{id:'bar_jack',name:'条纹鲹',en:'Bar Jack',cat:'salt',icon:'🏃',t:{lv2:30,lv3:45,lv4:60},r:'common',lure:'小铁板'},
{id:'horse_eye_jack',name:'马眼鲹',en:'Horse-Eye Jack',cat:'salt',icon:'🐴',t:{lv2:45,lv3:68,lv4:90},r:'uncommon',lure:'铁板'},
{id:'lookdown',name:'镜鱼',en:'Lookdown',cat:'salt',icon:'🪟',t:{lv2:25,lv3:38,lv4:50},r:'uncommon',lure:'小铁板'},
{id:'pompano_florida',name:'佛罗里达鲳参',en:'Florida Pompano',cat:'salt',icon:'🌴',t:{lv2:35,lv3:52,lv4:68},r:'uncommon',lure:'小铁板'},
{id:'crevalle_jack',name:'科氏鲹',en:'Crevalle Jack',cat:'salt',icon:'⚡',t:{lv2:50,lv3:75,lv4:100},r:'uncommon',lure:'铁板、波扒'},
{id:'yellowjack',name:'黄鲹',en:'Yellow Jack',cat:'salt',icon:'💛',t:{lv2:40,lv3:60,lv4:80},r:'uncommon',lure:'铁板'},
{id:'gnomefish',name:'侏鱼',en:'Gnomefish',cat:'salt',icon:'🧙',t:{lv2:20,lv3:30,lv4:40},r:'uncommon',lure:'软虫'},
{id:'flounder_gulf',name:'墨西哥湾比目鱼',en:'Gulf Flounder',cat:'salt',icon:'🌊',t:{lv2:35,lv3:52,lv4:68},r:'common',lure:'软虫、底层铁板'},
{id:'red_grouper',name:'红石斑',en:'Red Grouper',cat:'salt',icon:'🔴',t:{lv2:45,lv3:68,lv4:90},r:'uncommon',lure:'铁板、软虫'},
{id:'hapuku',name:'哈普库石斑',en:'Hapuku',cat:'salt',icon:'🇳🇿',t:{lv2:80,lv3:120,lv4:160},r:'epic',lure:'深场铁板'},
{id:'bass_european',name:'欧洲石鲈',en:'European Bass',cat:'salt',icon:'🇪🇺',t:{lv2:40,lv3:60,lv4:80},r:'uncommon',lure:'米诺、铅笔'},
{id:'meagre',name:'大白姑鱼',en:'Meagre',cat:'salt',icon:'🤍',t:{lv2:80,lv3:130,lv4:180},r:'epic',lure:'大型铁板、米诺'},
{id:'dentex',name:'鲷鱼',en:'Common Dentex',cat:'salt',icon:'🦷',t:{lv2:50,lv3:75,lv4:100},r:'rare',lure:'铁板'},
{id:'dusky_grouper',name:'暗色石斑',en:'Dusky Grouper',cat:'salt',icon:'🌑',t:{lv2:60,lv3:90,lv4:120},r:'rare',lure:'铁板'},
{id:'samson_fish',name:'萨姆森鱼',en:'Samson Fish',cat:'salt',icon:'💪',t:{lv2:80,lv3:120,lv4:160},r:'epic',lure:'铁板'},
{id:'giant_queenfish',name:'大型逆钩鲹',en:'Giant Queenfish',cat:'salt',icon:'👸',t:{lv2:55,lv3:82,lv4:110},r:'rare',lure:'铁板、铅笔'},
{id:'longtail_tuna',name:'长尾金枪鱼',en:'Longtail Tuna',cat:'salt',icon:'🐟',t:{lv2:70,lv3:105,lv4:140},r:'rare',lure:'铁板、波扒'},
{id:'kawakawa',name:'圆花鲣',en:'Kawakawa',cat:'salt',icon:'🌺',t:{lv2:40,lv3:60,lv4:80},r:'common',lure:'铁板、小波扒'},
{id:'frigate_mackerel',name:'舰艇鲭',en:'Frigate Mackerel',cat:'salt',icon:'⛵',t:{lv2:30,lv3:45,lv4:60},r:'common',lure:'小铁板'},
{id:'bullet_tuna',name:'子弹金枪',en:'Bullet Tuna',cat:'salt',icon:'🔫',t:{lv2:30,lv3:45,lv4:60},r:'common',lure:'小铁板'},
{id:'double_lined_mackerel',name:'双线马鲛',en:'Double-Lined Mackerel',cat:'salt',icon:'🔱',t:{lv2:55,lv3:82,lv4:110},r:'rare',lure:'高速拖钓'},
{id:'indo_pacific_mackerel',name:'印太鲭鱼',en:'Indo-Pacific Mackerel',cat:'salt',icon:'🌊',t:{lv2:35,lv3:52,lv4:70},r:'common',lure:'铁板'},
{id:'cero_mackerel',name:'塞罗马鲛',en:'Cero Mackerel',cat:'salt',icon:'🌴',t:{lv2:45,lv3:68,lv4:90},r:'uncommon',lure:'拖钓、铁板'},
{id:'narrowbarred_mackerel',name:'窄带马鲛',en:'Narrowbarred Spanish Mackerel',cat:'salt',icon:'〰️',t:{lv2:80,lv3:120,lv4:160},r:'rare',lure:'高速拖钓'},
{id:'spotted_mackerel',name:'斑点鲐',en:'Spotted Mackerel',cat:'salt',icon:'🔵',t:{lv2:40,lv3:60,lv4:80},r:'common',lure:'铁板'},
{id:'malabar_trevally',name:'马拉巴尔鲹',en:'Malabar Trevally',cat:'salt',icon:'🌴',t:{lv2:40,lv3:60,lv4:80},r:'uncommon',lure:'铁板'},
{id:'shadow_trevally',name:'阴影鲹',en:'Shadow Trevally',cat:'salt',icon:'🌑',t:{lv2:35,lv3:52,lv4:70},r:'uncommon',lure:'铁板'},
{id:'turrum',name:'图拉姆鲹',en:'Turrum',cat:'salt',icon:'🌊',t:{lv2:45,lv3:68,lv4:90},r:'rare',lure:'铁板'},
{id:'giant_kingfish',name:'国王鱼',en:'Giant Kingfish',cat:'salt',icon:'👑',t:{lv2:80,lv3:120,lv4:160},r:'epic',lure:'铁板、波扒'},
{id:'elagatis',name:'彩虹鲹',en:'Rainbow Runner',cat:'salt',icon:'🌈',t:{lv2:45,lv3:68,lv4:90},r:'uncommon',lure:'铁板'},
{id:'cobia_indopacific',name:'印太军曹鱼',en:'Indo-Pacific Cobia',cat:'salt',icon:'🎖️',t:{lv2:65,lv3:98,lv4:132},r:'rare',lure:'大型软饵'},
{id:'african_pompano2',name:'帆鱼鲳参',en:'Pennantfish',cat:'salt',icon:'🪁',t:{lv2:45,lv3:68,lv4:90},r:'rare',lure:'深场铁板'},
{id:'wahoo_pacific',name:'太平洋横带鲅',en:'Pacific Wahoo',cat:'salt',icon:'🏎️',t:{lv2:90,lv3:140,lv4:190},r:'epic',lure:'高速拖钓'},
{id:'dorado_pacific',name:'太平洋鲯鳅',en:'Pacific Mahi-mahi',cat:'salt',icon:'🌊',t:{lv2:55,lv3:82,lv4:110},r:'rare',lure:'拖钓、水面路亚'},
{id:'ladyfish',name:'猎鲦鱼',en:'Ladyfish',cat:'salt',icon:'💃',t:{lv2:35,lv3:52,lv4:68},r:'common',lure:'小铁板、米诺'},
{id:'oxeye_tarpon',name:'大眼鲢',en:'Oxeye Tarpon',cat:'salt',icon:'👁️',t:{lv2:60,lv3:90,lv4:120},r:'rare',lure:'大型软饵'},
{id:'milkfish',name:'遮目鱼',en:'Milkfish',cat:'salt',icon:'🥛',t:{lv2:60,lv3:90,lv4:120},r:'uncommon',lure:'飞蝇、软饵'},

// ===== 远洋/海钓补充（sea）=====
{id:'atlantic_bonito',name:'大西洋鲣',en:'Atlantic Bonito',cat:'sea',icon:'🌊',t:{lv2:50,lv3:75,lv4:100},r:'uncommon',lure:'铁板、拖钓'},
{id:'little_tunny',name:'小金枪鱼',en:'Little Tunny',cat:'sea',icon:'🐟',t:{lv2:50,lv3:75,lv4:100},r:'uncommon',lure:'铁板、拖钓'},
{id:'blackfin_tuna',name:'黑鳍金枪鱼',en:'Blackfin Tuna',cat:'sea',icon:'⬛',t:{lv2:55,lv3:82,lv4:110},r:'rare',lure:'铁板、拖钓'},
{id:'pacific_bluefin',name:'太平洋蓝鳍金枪鱼',en:'Pacific Bluefin Tuna',cat:'sea',icon:'🔷',t:{lv2:100,lv3:180,lv4:300},r:'legendary',lure:'大型铁板、拖钓'},
{id:'southern_bluefin',name:'南方蓝鳍金枪鱼',en:'Southern Bluefin Tuna',cat:'sea',icon:'💙',t:{lv2:100,lv3:170,lv4:270},r:'legendary',lure:'大型铁板、拖钓'},
{id:'atlantic_sailfish',name:'大西洋旗鱼',en:'Atlantic Sailfish',cat:'sea',icon:'⛵',t:{lv2:150,lv3:220,lv4:300},r:'legendary',lure:'拖钓'},
{id:'indo_sailfish',name:'印太旗鱼',en:'Indo-Pacific Sailfish',cat:'sea',icon:'⛵',t:{lv2:160,lv3:240,lv4:340},r:'legendary',lure:'拖钓'},
{id:'broadbill',name:'剑旗鱼',en:'Broadbill Swordfish',cat:'sea',icon:'⚔️',t:{lv2:220,lv3:340,lv4:500},r:'legendary',lure:'深海夜钓大饵'},
{id:'spearfish_longbill',name:'长嘴枪鱼',en:'Longbill Spearfish',cat:'sea',icon:'🏹',t:{lv2:130,lv3:190,lv4:250},r:'legendary',lure:'拖钓'},
{id:'shortbill_spearfish',name:'短嘴枪鱼',en:'Shortbill Spearfish',cat:'sea',icon:'🗡️',t:{lv2:120,lv3:180,lv4:240},r:'legendary',lure:'拖钓'},
{id:'roundscale_spearfish',name:'圆鳞枪鱼',en:'Roundscale Spearfish',cat:'sea',icon:'⚡',t:{lv2:125,lv3:185,lv4:245},r:'legendary',lure:'拖钓'},
{id:'yellowfin_tuna2',name:'大型黄鳍金枪鱼',en:'Giant Yellowfin Tuna',cat:'sea',icon:'🌟',t:{lv2:100,lv3:170,lv4:250},r:'legendary',lure:'大型铁板、拖钓'},
{id:'atlantic_bluefin2',name:'北大西洋蓝鳍',en:'Atlantic Bluefin Tuna',cat:'sea',icon:'💎',t:{lv2:150,lv3:250,lv4:400},r:'legendary',lure:'大型铁板、拖钓'},
{id:'yellowfin_grouper2',name:'深场黄鳍石斑',en:'Deep Yellowfin Grouper',cat:'sea',icon:'💛',t:{lv2:55,lv3:82,lv4:110},r:'rare',lure:'深场铁板'},
{id:'ruby_snapper2',name:'深场红宝石笛鲷',en:'Deep Ruby Snapper',cat:'sea',icon:'♦️',t:{lv2:45,lv3:68,lv4:90},r:'rare',lure:'深场铁板'},
{id:'crimson_snapper',name:'深红笛鲷',en:'Crimson Snapper',cat:'sea',icon:'❤️',t:{lv2:40,lv3:60,lv4:80},r:'rare',lure:'深场铁板'},
{id:'emperor_red',name:'红龙占',en:'Red Emperor',cat:'sea',icon:'🔴',t:{lv2:60,lv3:90,lv4:120},r:'rare',lure:'深场铁板'},
{id:'nannygai',name:'南盖笛鲷',en:'Nannygai',cat:'sea',icon:'🦐',t:{lv2:40,lv3:60,lv4:80},r:'uncommon',lure:'深场铁板'},
{id:'bass_giant_sea',name:'巨型海鲈',en:'Giant Sea Bass',cat:'sea',icon:'🌊',t:{lv2:100,lv3:160,lv4:220},r:'legendary',lure:'大型铁板'},
{id:'amberjack_lesser',name:'小章红',en:'Lesser Amberjack',cat:'sea',icon:'🔱',t:{lv2:40,lv3:60,lv4:80},r:'uncommon',lure:'铁板'},
{id:'banded_amberjack',name:'带纹章红',en:'Banded Amberjack',cat:'sea',icon:'🎀',t:{lv2:55,lv3:82,lv4:110},r:'rare',lure:'铁板'},
{id:'yellowtail_amberjack',name:'黄尾鰤',en:'Yellowtail Amberjack',cat:'sea',icon:'🟡',t:{lv2:60,lv3:90,lv4:120},r:'rare',lure:'铁板'},
{id:'kampachi',name:'间八鱼',en:'Kampachi',cat:'sea',icon:'🇯🇵',t:{lv2:65,lv3:98,lv4:132},r:'rare',lure:'铁板'},
{id:'hiramasa',name:'平政鱼',en:'Hiramasa',cat:'sea',icon:'⛩️',t:{lv2:70,lv3:105,lv4:140},r:'epic',lure:'铁板、铅笔'},
{id:'kinmedai',name:'金目鲷',en:'Kinmedai',cat:'sea',icon:'🔴',t:{lv2:35,lv3:52,lv4:70},r:'rare',lure:'深场铁板'},
{id:'alfonsino',name:'阿方索鱼',en:'Alfonsino',cat:'sea',icon:'🌹',t:{lv2:40,lv3:60,lv4:80},r:'rare',lure:'深场铁板'},
{id:'oilfish',name:'油鱼',en:'Oilfish',cat:'sea',icon:'🫙',t:{lv2:80,lv3:130,lv4:180},r:'rare',lure:'深场大型铁板'},
{id:'escolar',name:'蛇鲭',en:'Escolar',cat:'sea',icon:'🐍',t:{lv2:80,lv3:130,lv4:175},r:'rare',lure:'深场铁板'},
{id:'wahoo3',name:'夏威夷横带鲅',en:'Hawaiian Wahoo',cat:'sea',icon:'🌺',t:{lv2:100,lv3:155,lv4:210},r:'epic',lure:'高速拖钓'},
{id:'giant_barracuda',name:'巨型梭鱼',en:'Great Barracuda',cat:'sea',icon:'🗡️',t:{lv2:80,lv3:125,lv4:170},r:'epic',lure:'铁板、铅笔'},
{id:'shark_bull',name:'公牛鲨',en:'Bull Shark',cat:'sea',icon:'🦈',t:{lv2:180,lv3:270,lv4:350},r:'legendary',lure:'大型软饵拖钓'},
{id:'shark_tiger',name:'虎鲨',en:'Tiger Shark',cat:'sea',icon:'🐯',t:{lv2:200,lv3:300,lv4:420},r:'legendary',lure:'大型拖钓'},
{id:'shark_hammerhead',name:'双髻鲨',en:'Hammerhead Shark',cat:'sea',icon:'🔨',t:{lv2:200,lv3:300,lv4:400},r:'legendary',lure:'大型拖钓'},
{id:'shark_thresher',name:'长尾鲨',en:'Thresher Shark',cat:'sea',icon:'🌀',t:{lv2:200,lv3:320,lv4:450},r:'legendary',lure:'拖钓'},
{id:'shark_spinner',name:'旋转鲨',en:'Spinner Shark',cat:'sea',icon:'🌀',t:{lv2:160,lv3:240,lv4:320},r:'rare',lure:'铁板'},
{id:'shark_blacktip',name:'黑鳍鲨',en:'Blacktip Shark',cat:'sea',icon:'⬛',t:{lv2:150,lv3:220,lv4:290},r:'rare',lure:'大型铁板'},
{id:'trevally_lowly',name:'低鲹',en:'Lowly Trevally',cat:'sea',icon:'🌊',t:{lv2:25,lv3:38,lv4:52},r:'common',lure:'小铁板'},
{id:'coronation_trout',name:'加冕鲈',en:'Coronation Trout',cat:'sea',icon:'👑',t:{lv2:35,lv3:52,lv4:70},r:'rare',lure:'铁板'},
{id:'humphead_wrasse',name:'波纹唇鱼',en:'Humphead Wrasse',cat:'sea',icon:'🐠',t:{lv2:80,lv3:130,lv4:180},r:'legendary',lure:'大型软饵'},
{id:'maori_wrasse',name:'毛利唇鱼',en:'Maori Wrasse',cat:'sea',icon:'🌊',t:{lv2:50,lv3:75,lv4:100},r:'epic',lure:'铁板'},
{id:'spottail_bass',name:'斑尾石鲈',en:'Spottail Bass',cat:'sea',icon:'🔵',t:{lv2:40,lv3:60,lv4:80},r:'uncommon',lure:'铁板、软虫'},
{id:'golden_snapper',name:'金笛鲷',en:'Golden Snapper',cat:'sea',icon:'💰',t:{lv2:45,lv3:68,lv4:90},r:'rare',lure:'深场铁板'},
{id:'flame_snapper',name:'火焰笛鲷',en:'Flame Snapper',cat:'sea',icon:'🔥',t:{lv2:40,lv3:60,lv4:80},r:'rare',lure:'深场铁板'},
{id:'rankin_cod',name:'兰金鳕',en:'Rankin Cod',cat:'sea',icon:'🌊',t:{lv2:50,lv3:75,lv4:100},r:'rare',lure:'铁板'},
{id:'bass_striped_sea',name:'海洋条纹石鲈',en:'Giant Sea Perch',cat:'sea',icon:'🌊',t:{lv2:70,lv3:105,lv4:140},r:'epic',lure:'大型铁板'},
];
